// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: UI_Blank_Screen

#ifndef IDLE_UI_H
#define IDLE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "idle_ui_helpers.h"

///////////////////// SCREENS ////////////////////

#include "idle_ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * idle_ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(idle_ui_font_fuenteMontserratM16Tildes);

// UI INIT
void idle_ui_init(void);
void idle_ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
