// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: UI_Blank_Screen

#ifndef IDLE_UI_SCREEN1_H
#define IDLE_UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: idle_ui_Screen1
extern void idle_ui_Screen1_screen_init(void);
extern void idle_ui_Screen1_screen_destroy(void);
extern lv_obj_t * idle_ui_Screen1;
extern lv_obj_t * idle_ui_Label1;
extern lv_obj_t * idle_ui_Spinner1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

