// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: UI_Blank_Screen

#include "idle_ui.h"

lv_obj_t * idle_ui_Screen1 = NULL;
lv_obj_t * idle_ui_Label1 = NULL;
lv_obj_t * idle_ui_Spinner1 = NULL;
// event funtions

// build funtions

void idle_ui_Screen1_screen_init(void)
{
    idle_ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(idle_ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    idle_ui_Label1 = lv_label_create(idle_ui_Screen1);
    lv_obj_set_width(idle_ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(idle_ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(idle_ui_Label1, 0);
    lv_obj_set_y(idle_ui_Label1, -50);
    lv_obj_set_align(idle_ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(idle_ui_Label1, "Esperando conexión\nde módulo");
    lv_obj_set_style_text_align(idle_ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(idle_ui_Label1, &idle_ui_font_fuenteMontserratM16Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    idle_ui_Spinner1 = lv_spinner_create(idle_ui_Screen1);
    //lv_spinner_set_anim_params(idle_ui_Spinner1, 1000, 90);
    lv_obj_set_width(idle_ui_Spinner1, 90);
    lv_obj_set_height(idle_ui_Spinner1, 90);
    lv_obj_set_x(idle_ui_Spinner1, 0);
    lv_obj_set_y(idle_ui_Spinner1, 70);
    lv_obj_set_align(idle_ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(idle_ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(idle_ui_Spinner1, lv_color_hex(0xBBB9B9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(idle_ui_Spinner1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void idle_ui_Screen1_screen_destroy(void)
{
    if(idle_ui_Screen1) lv_obj_del(idle_ui_Screen1);

    // NULL screen variables
    idle_ui_Screen1 = NULL;
    idle_ui_Label1 = NULL;
    idle_ui_Spinner1 = NULL;

}
