// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: UI_TFI

#ifndef UI_SCREEN5_H
#define UI_SCREEN5_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen5
extern void ui_Screen5_screen_init(void);
extern void ui_Screen5_screen_destroy(void);
extern lv_obj_t * ui_Screen5;
extern void ui_event_ButtonReturn4(lv_event_t * e);
extern lv_obj_t * ui_ButtonReturn4;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_setPointValue;
extern void ui_event_SliderSP(lv_event_t * e);
extern lv_obj_t * ui_SliderSP;
extern void ui_event_ButtonReturnDefault3(lv_event_t * e);
extern lv_obj_t * ui_ButtonReturnDefault3;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

