// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: inversor_UI

#ifndef INVERTER_UI_H
#define INVERTER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "inverter_ui_helpers.h"
#include "inverter_ui_events.h"

///////////////////// SCREENS ////////////////////

#include "inverter_ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * inverter_ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(inverter_ui_img_images_inversor_scaled_png);    // assets/images/inversor_scaled.png

// FONTS
LV_FONT_DECLARE(inverter_ui_font_fontRobotoBold18Tildes);
LV_FONT_DECLARE(inverter_ui_font_fontRobotoMedium16Tildes);

// UI INIT
void inverter_ui_init(void);
void inverter_ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
