// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: inverter_UI

#include "inverter_ui.h"

lv_obj_t * inverter_ui_Screen1 = NULL;
lv_obj_t * inverter_ui_Label1 = NULL;
lv_obj_t * inverter_ui_Image3 = NULL;
lv_obj_t * inverter_ui_Label2 = NULL;
// event funtions

// build funtions

void inverter_ui_Screen1_screen_init(void)
{
    inverter_ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(inverter_ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    inverter_ui_Label1 = lv_label_create(inverter_ui_Screen1);
    lv_obj_set_width(inverter_ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(inverter_ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(inverter_ui_Label1, 0);
    lv_obj_set_y(inverter_ui_Label1, -120);
    lv_obj_set_align(inverter_ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(inverter_ui_Label1, "Módulo inversor de onda \ncuadrada con medio puente\nde transistores");
    lv_obj_set_style_text_align(inverter_ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(inverter_ui_Label1, &inverter_ui_font_fuenteMontserratM16Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    inverter_ui_Image3 = lv_image_create(inverter_ui_Screen1);
    lv_image_set_src(inverter_ui_Image3, &inverter_ui_img_circuito_png);
    lv_obj_set_width(inverter_ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(inverter_ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(inverter_ui_Image3, 0);
    lv_obj_set_y(inverter_ui_Image3, 70);
    lv_obj_set_align(inverter_ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(inverter_ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(inverter_ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(inverter_ui_Image3, 250);

    inverter_ui_Label2 = lv_label_create(inverter_ui_Screen1);
    lv_obj_set_width(inverter_ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(inverter_ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(inverter_ui_Label2, 0);
    lv_obj_set_y(inverter_ui_Label2, -60);
    lv_obj_set_align(inverter_ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(inverter_ui_Label2, "Para modificar los valores \npermitidos en este módulo, \nrevisar manual de usuario");
    lv_obj_set_style_text_align(inverter_ui_Label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(inverter_ui_Label2, &inverter_ui_font_fuenteMontserrat14Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void inverter_ui_Screen1_screen_destroy(void)
{
    if(inverter_ui_Screen1) lv_obj_del(inverter_ui_Screen1);

    // NULL screen variables
    inverter_ui_Screen1 = NULL;
    inverter_ui_Label1 = NULL;
    inverter_ui_Image3 = NULL;
    inverter_ui_Label2 = NULL;

}
