// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: inverter_UI

#include "inverter_ui.h"
#include "inverter_ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * inverter_ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void inverter_ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    inverter_ui_Screen1_screen_init();
    inverter_ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(inverter_ui_Screen1);
}

void inverter_ui_destroy(void)
{
    inverter_ui_Screen1_screen_destroy();
}
