// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: inversor_UI

#ifndef INVERTER_UI_SCREEN1_H
#define INVERTER_UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: inverter_ui_Screen1
extern void inverter_ui_Screen1_screen_init(void);
extern void inverter_ui_Screen1_screen_destroy(void);
extern lv_obj_t * inverter_ui_Screen1;
extern lv_obj_t * inverter_ui_Label1;
extern lv_obj_t * inverter_ui_Image3;
extern lv_obj_t * inverter_ui_Panel1;
extern lv_obj_t * inverter_ui_Label2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

