// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: dimmer_UI

#ifndef DIMMER_UI_SCREEN5_H
#define DIMMER_UI_SCREEN5_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: dimmer_ui_Screen5
extern void dimmer_ui_Screen5_screen_init(void);
extern void dimmer_ui_Screen5_screen_destroy(void);
extern lv_obj_t * dimmer_ui_Screen5;
extern lv_obj_t * dimmer_ui_Label10;
extern void dimmer_ui_event_SliderSP(lv_event_t * e);
extern lv_obj_t * dimmer_ui_SliderSP;
extern lv_obj_t * dimmer_ui_Label11;
extern lv_obj_t * dimmer_ui_LabelSP;
extern void dimmer_ui_event_ButtonReturn4(lv_event_t * e);
extern lv_obj_t * dimmer_ui_ButtonReturn4;
extern lv_obj_t * dimmer_ui_cicloPositivo;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

