// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: dimmer_UI

#include "dimmer_ui.h"

lv_obj_t * dimmer_ui_Screen1 = NULL;
lv_obj_t * dimmer_ui_Label1 = NULL;
lv_obj_t * dimmer_ui_ButtonAnalogical = NULL;
lv_obj_t * dimmer_ui_Label2 = NULL;
lv_obj_t * dimmer_ui_ButtonDigital = NULL;
lv_obj_t * dimmer_ui_Label3 = NULL;
lv_obj_t * dimmer_ui_Label14 = NULL;
lv_obj_t * dimmer_ui_Image1 = NULL;
// event funtions
void dimmer_ui_event_ButtonAnalogical(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&dimmer_ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &dimmer_ui_Screen2_screen_init);
        _ui_screen_delete(&dimmer_ui_Screen1);
    }
}

void dimmer_ui_event_ButtonDigital(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&dimmer_ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &dimmer_ui_Screen3_screen_init);
        _ui_screen_delete(&dimmer_ui_Screen1);
    }
}

// build funtions

void dimmer_ui_Screen1_screen_init(void)
{
    dimmer_ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(dimmer_ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    dimmer_ui_Label1 = lv_label_create(dimmer_ui_Screen1);
    lv_obj_set_width(dimmer_ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(dimmer_ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(dimmer_ui_Label1, 0);
    lv_obj_set_y(dimmer_ui_Label1, -80);
    lv_obj_set_align(dimmer_ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(dimmer_ui_Label1, "Modo de Control");
    lv_obj_set_style_text_font(dimmer_ui_Label1, &dimmer_ui_font_fontMontserratM14Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    dimmer_ui_ButtonAnalogical = lv_button_create(dimmer_ui_Screen1);
    lv_obj_set_width(dimmer_ui_ButtonAnalogical, 100);
    lv_obj_set_height(dimmer_ui_ButtonAnalogical, 50);
    lv_obj_set_x(dimmer_ui_ButtonAnalogical, -60);
    lv_obj_set_y(dimmer_ui_ButtonAnalogical, -40);
    lv_obj_set_align(dimmer_ui_ButtonAnalogical, LV_ALIGN_CENTER);
    lv_obj_add_flag(dimmer_ui_ButtonAnalogical, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(dimmer_ui_ButtonAnalogical, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    dimmer_ui_Label2 = lv_label_create(dimmer_ui_ButtonAnalogical);
    lv_obj_set_width(dimmer_ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(dimmer_ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(dimmer_ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(dimmer_ui_Label2, "Analógico");
    lv_obj_set_style_text_font(dimmer_ui_Label2, &dimmer_ui_font_fontMontserratM14Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    dimmer_ui_ButtonDigital = lv_button_create(dimmer_ui_Screen1);
    lv_obj_set_width(dimmer_ui_ButtonDigital, 100);
    lv_obj_set_height(dimmer_ui_ButtonDigital, 50);
    lv_obj_set_x(dimmer_ui_ButtonDigital, 60);
    lv_obj_set_y(dimmer_ui_ButtonDigital, -40);
    lv_obj_set_align(dimmer_ui_ButtonDigital, LV_ALIGN_CENTER);
    lv_obj_add_flag(dimmer_ui_ButtonDigital, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(dimmer_ui_ButtonDigital, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    dimmer_ui_Label3 = lv_label_create(dimmer_ui_ButtonDigital);
    lv_obj_set_width(dimmer_ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(dimmer_ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(dimmer_ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(dimmer_ui_Label3, "Digital");
    lv_obj_set_style_text_font(dimmer_ui_Label3, &dimmer_ui_font_fontMontserratM14Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    dimmer_ui_Label14 = lv_label_create(dimmer_ui_Screen1);
    lv_obj_set_width(dimmer_ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(dimmer_ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(dimmer_ui_Label14, 0);
    lv_obj_set_y(dimmer_ui_Label14, -120);
    lv_obj_set_align(dimmer_ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(dimmer_ui_Label14, "Módulo recortador\nde onda");
    lv_obj_set_style_text_align(dimmer_ui_Label14, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(dimmer_ui_Label14, &dimmer_ui_font_fontMontserratM18Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    dimmer_ui_Image1 = lv_image_create(dimmer_ui_Screen1);
    lv_image_set_src(dimmer_ui_Image1, &dimmer_ui_img_images_dimmer_png);
    lv_obj_set_width(dimmer_ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(dimmer_ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(dimmer_ui_Image1, 0);
    lv_obj_set_y(dimmer_ui_Image1, 74);
    lv_obj_set_align(dimmer_ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(dimmer_ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(dimmer_ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(dimmer_ui_Image1, 220);

    lv_obj_add_event_cb(dimmer_ui_ButtonAnalogical, dimmer_ui_event_ButtonAnalogical, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(dimmer_ui_ButtonDigital, dimmer_ui_event_ButtonDigital, LV_EVENT_ALL, NULL);

}

void dimmer_ui_Screen1_screen_destroy(void)
{
    if(dimmer_ui_Screen1) lv_obj_del(dimmer_ui_Screen1);

    // NULL screen variables
    dimmer_ui_Screen1 = NULL;
    dimmer_ui_Label1 = NULL;
    dimmer_ui_ButtonAnalogical = NULL;
    dimmer_ui_Label2 = NULL;
    dimmer_ui_ButtonDigital = NULL;
    dimmer_ui_Label3 = NULL;
    dimmer_ui_Label14 = NULL;
    dimmer_ui_Image1 = NULL;

}
