// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: dimmer_UI

#ifndef DIMMER_UI_H
#define DIMMER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "dimmer_ui_helpers.h"
#include "dimmer_ui_events.h"

///////////////////// SCREENS ////////////////////

#include "dimmer_ui_Screen1.h"
#include "dimmer_ui_Screen2.h"
#include "dimmer_ui_Screen3.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * dimmer_ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(dimmer_ui_img_images_dimmer_scaled_png);    // assets/images/dimmer_scaled.png
LV_IMG_DECLARE(dimmer_ui_img_images_arrow_png);    // assets/images/arrow.png
LV_IMG_DECLARE(dimmer_ui_img_images_completo_sf_png);    // assets/images/completo_sf.png

// FONTS
LV_FONT_DECLARE(dimmer_ui_font_fontRobotoBold16Tildes);
LV_FONT_DECLARE(dimmer_ui_font_fontRobotoBold18Tildes);
LV_FONT_DECLARE(dimmer_ui_font_fontRobotoMedium14Tildes);
LV_FONT_DECLARE(dimmer_ui_font_fontRobotoMedium16Tildes);
LV_FONT_DECLARE(dimmer_ui_font_fontRobotoRegular14Tildes);

// UI INIT
void dimmer_ui_init(void);
void dimmer_ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
