// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: dimmer_UI

#ifndef DIMMER_UI_SCREEN3_H
#define DIMMER_UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: dimmer_ui_Screen3
extern void dimmer_ui_Screen3_screen_init(void);
extern void dimmer_ui_Screen3_screen_destroy(void);
extern lv_obj_t * dimmer_ui_Screen3;
extern lv_obj_t * dimmer_ui_Label8;
extern void dimmer_ui_event_SliderCC(lv_event_t * e);
extern lv_obj_t * dimmer_ui_SliderCC;
extern lv_obj_t * dimmer_ui_Label9;
extern lv_obj_t * dimmer_ui_LabelCC;
extern void dimmer_ui_event_ButtonReturn3(lv_event_t * e);
extern lv_obj_t * dimmer_ui_ButtonReturn3;
extern lv_obj_t * dimmer_ui_cicloCompleto;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

