// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: dimmer_UI

#ifndef DIMMER_UI_SCREEN2_H
#define DIMMER_UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: dimmer_ui_Screen2
extern void dimmer_ui_Screen2_screen_init(void);
extern void dimmer_ui_Screen2_screen_destroy(void);
extern lv_obj_t * dimmer_ui_Screen2;
extern void dimmer_ui_event_ButtonReturn1(lv_event_t * e);
extern lv_obj_t * dimmer_ui_ButtonReturn1;
extern lv_obj_t * dimmer_ui_Label4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

