// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: dimmer_UI

#ifndef DIMMER_UI_SCREEN1_H
#define DIMMER_UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: dimmer_ui_Screen1
extern void dimmer_ui_Screen1_screen_init(void);
extern void dimmer_ui_Screen1_screen_destroy(void);
extern lv_obj_t * dimmer_ui_Screen1;
extern lv_obj_t * dimmer_ui_Label1;
extern void dimmer_ui_event_ButtonAnalogical(lv_event_t * e);
extern lv_obj_t * dimmer_ui_ButtonAnalogical;
extern lv_obj_t * dimmer_ui_Label2;
extern void dimmer_ui_event_ButtonDigital(lv_event_t * e);
extern lv_obj_t * dimmer_ui_ButtonDigital;
extern lv_obj_t * dimmer_ui_Label3;
extern lv_obj_t * dimmer_ui_Label14;
extern lv_obj_t * dimmer_ui_Image1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

