// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: dimmer_UI

#include "dimmer_ui.h"

lv_obj_t * dimmer_ui_Screen5 = NULL;
lv_obj_t * dimmer_ui_Label10 = NULL;
lv_obj_t * dimmer_ui_SliderSP = NULL;
lv_obj_t * dimmer_ui_Label11 = NULL;
lv_obj_t * dimmer_ui_LabelSP = NULL;
lv_obj_t * dimmer_ui_ButtonReturn4 = NULL;
// event funtions
void dimmer_ui_event_SliderSP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        update_time_label(e);
    }
}

void dimmer_ui_event_ButtonReturn4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&dimmer_ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &dimmer_ui_Screen3_screen_init);
        _ui_screen_delete(&dimmer_ui_Screen5);
    }
}

// build funtions

void dimmer_ui_Screen5_screen_init(void)
{
    dimmer_ui_Screen5 = lv_obj_create(NULL);
    lv_obj_remove_flag(dimmer_ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    dimmer_ui_Label10 = lv_label_create(dimmer_ui_Screen5);
    lv_obj_set_width(dimmer_ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(dimmer_ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(dimmer_ui_Label10, 0);
    lv_obj_set_y(dimmer_ui_Label10, -50);
    lv_obj_set_align(dimmer_ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(dimmer_ui_Label10, "Semiciclo Positivo");
    lv_obj_set_style_text_font(dimmer_ui_Label10, &dimmer_ui_font_fontMontserratM18Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    dimmer_ui_SliderSP = lv_slider_create(dimmer_ui_Screen5);
    lv_slider_set_range(dimmer_ui_SliderSP, 0, 50);
    lv_slider_set_value(dimmer_ui_SliderSP, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(dimmer_ui_SliderSP) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(dimmer_ui_SliderSP, 1, LV_ANIM_OFF);
    lv_obj_set_width(dimmer_ui_SliderSP, 150);
    lv_obj_set_height(dimmer_ui_SliderSP, 10);
    lv_obj_set_x(dimmer_ui_SliderSP, 0);
    lv_obj_set_y(dimmer_ui_SliderSP, 50);
    lv_obj_set_align(dimmer_ui_SliderSP, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(dimmer_ui_SliderSP, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(dimmer_ui_SliderSP,
                                                                                               lv_obj_get_style_pad_right(dimmer_ui_SliderSP, LV_PART_MAIN) + 1, LV_PART_MAIN);
    dimmer_ui_Label11 = lv_label_create(dimmer_ui_Screen5);
    lv_obj_set_width(dimmer_ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(dimmer_ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(dimmer_ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(dimmer_ui_Label11, "Tiempo de disparo");
    lv_obj_set_style_text_font(dimmer_ui_Label11, &dimmer_ui_font_fontMontserratM14Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    dimmer_ui_LabelSP = lv_label_create(dimmer_ui_Screen5);
    lv_obj_set_width(dimmer_ui_LabelSP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(dimmer_ui_LabelSP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(dimmer_ui_LabelSP, 0);
    lv_obj_set_y(dimmer_ui_LabelSP, 30);
    lv_obj_set_align(dimmer_ui_LabelSP, LV_ALIGN_CENTER);
    lv_label_set_text(dimmer_ui_LabelSP, "0 ms");
    lv_obj_set_style_text_font(dimmer_ui_LabelSP, &dimmer_ui_font_fontMontserratM14Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    dimmer_ui_ButtonReturn4 = lv_button_create(dimmer_ui_Screen5);
    lv_obj_set_width(dimmer_ui_ButtonReturn4, 45);
    lv_obj_set_height(dimmer_ui_ButtonReturn4, 40);
    lv_obj_add_flag(dimmer_ui_ButtonReturn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(dimmer_ui_ButtonReturn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(dimmer_ui_ButtonReturn4, &dimmer_ui_img_images_arrow_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(dimmer_ui_ButtonReturn4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(dimmer_ui_ButtonReturn4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(dimmer_ui_SliderSP, dimmer_ui_event_SliderSP, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(dimmer_ui_ButtonReturn4, dimmer_ui_event_ButtonReturn4, LV_EVENT_ALL, NULL);

}

void dimmer_ui_Screen5_screen_destroy(void)
{
    if(dimmer_ui_Screen5) lv_obj_del(dimmer_ui_Screen5);

    // NULL screen variables
    dimmer_ui_Screen5 = NULL;
    dimmer_ui_Label10 = NULL;
    dimmer_ui_SliderSP = NULL;
    dimmer_ui_Label11 = NULL;
    dimmer_ui_LabelSP = NULL;
    dimmer_ui_ButtonReturn4 = NULL;

}
