// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: dimmer_UI

#ifndef DIMMER_UI_EVENTS_H
#define DIMMER_UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void dimmer_control_analog(lv_event_t * e);
void dimmer_control_digital(lv_event_t * e);
void dimmer_return(lv_event_t * e);
void update_time_label(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
