// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: dimmer_UI

#ifndef DIMMER_UI_SCREEN6_H
#define DIMMER_UI_SCREEN6_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: dimmer_ui_Screen6
extern void dimmer_ui_Screen6_screen_init(void);
extern void dimmer_ui_Screen6_screen_destroy(void);
extern lv_obj_t * dimmer_ui_Screen6;
extern lv_obj_t * dimmer_ui_Label12;
extern void dimmer_ui_event_SliderSN(lv_event_t * e);
extern lv_obj_t * dimmer_ui_SliderSN;
extern lv_obj_t * dimmer_ui_Label13;
extern lv_obj_t * dimmer_ui_LabelSN;
extern void dimmer_ui_event_ButtonReturn5(lv_event_t * e);
extern lv_obj_t * dimmer_ui_ButtonReturn5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

