// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: dimmer_UI

#include "dimmer_ui.h"

lv_obj_t * dimmer_ui_Screen2 = NULL;
lv_obj_t * dimmer_ui_ButtonReturn1 = NULL;
lv_obj_t * dimmer_ui_Label4 = NULL;
// event funtions
void dimmer_ui_event_ButtonReturn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&dimmer_ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &dimmer_ui_Screen1_screen_init);
        _ui_screen_delete(&dimmer_ui_Screen2);
        dimmer_return(e);
    }
}

// build funtions

void dimmer_ui_Screen2_screen_init(void)
{
    dimmer_ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(dimmer_ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    dimmer_ui_ButtonReturn1 = lv_button_create(dimmer_ui_Screen2);
    lv_obj_set_width(dimmer_ui_ButtonReturn1, 45);
    lv_obj_set_height(dimmer_ui_ButtonReturn1, 40);
    lv_obj_add_flag(dimmer_ui_ButtonReturn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(dimmer_ui_ButtonReturn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(dimmer_ui_ButtonReturn1, &dimmer_ui_img_images_arrow_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(dimmer_ui_ButtonReturn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(dimmer_ui_ButtonReturn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    dimmer_ui_Label4 = lv_label_create(dimmer_ui_Screen2);
    lv_obj_set_width(dimmer_ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(dimmer_ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(dimmer_ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(dimmer_ui_Label4,
                      "Se encuentra dentro del control \nanalógico, utilice el \npotenciometro que se encuentra \nen el gabinete para poder \nmodificar el ángulo de disparo");
    lv_obj_set_style_text_letter_space(dimmer_ui_Label4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(dimmer_ui_Label4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(dimmer_ui_Label4, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(dimmer_ui_Label4, &dimmer_ui_font_fontRobotoMedium16Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(dimmer_ui_ButtonReturn1, dimmer_ui_event_ButtonReturn1, LV_EVENT_ALL, NULL);

}

void dimmer_ui_Screen2_screen_destroy(void)
{
    if(dimmer_ui_Screen2) lv_obj_del(dimmer_ui_Screen2);

    // NULL screen variables
    dimmer_ui_Screen2 = NULL;
    dimmer_ui_ButtonReturn1 = NULL;
    dimmer_ui_Label4 = NULL;

}
