// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: buck_UI

#include "buck_ui.h"

#include "gpio_definition.h"
#include "driver/gpio.h"
#include "buck_control.h"

void controlFixedPWM(lv_event_t * e)
{
	set_control_mode(CONTROL_MODE_FIXED_PWM);
}

void controlPID(lv_event_t * e)
{
	set_control_mode(CONTROL_MODE_PID);
}

void resistive_load(lv_event_t * e)
{
	gpio_set_level(PIN_NUM_RELAY, false);
}

void inductive_load(lv_event_t * e)
{
	gpio_set_level(PIN_NUM_RELAY, true);
}
