// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: buck_UI

#ifndef BUCK_UI_SCREEN5_H
#define BUCK_UI_SCREEN5_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: buck_ui_Screen5
extern void buck_ui_Screen5_screen_init(void);
extern void buck_ui_Screen5_screen_destroy(void);
extern lv_obj_t * buck_ui_Screen5;
extern void buck_ui_event_ButtonReturn4(lv_event_t * e);
extern lv_obj_t * buck_ui_ButtonReturn4;
extern lv_obj_t * buck_ui_Panel3;
extern lv_obj_t * buck_ui_Label11;
extern void buck_ui_event_SliderSP(lv_event_t * e);
extern lv_obj_t * buck_ui_SliderSP;
extern lv_obj_t * buck_ui_setPointValue;
extern void buck_ui_event_ButtonReturnDefault3(lv_event_t * e);
extern lv_obj_t * buck_ui_ButtonReturnDefault3;
extern lv_obj_t * buck_ui_Label12;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

