// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: buck_UI

#include "buck_ui.h"

lv_obj_t * buck_ui_Screen6 = NULL;
lv_obj_t * buck_ui_ButtonReturn5 = NULL;
lv_obj_t * buck_ui_Panel4 = NULL;
lv_obj_t * buck_ui_Label16 = NULL;
lv_obj_t * buck_ui_Button5 = NULL;
lv_obj_t * buck_ui_Label17 = NULL;
lv_obj_t * buck_ui_Button6 = NULL;
lv_obj_t * buck_ui_Label18 = NULL;
lv_obj_t * buck_ui_Label13 = NULL;
lv_obj_t * buck_ui_LabelTypeLoad = NULL;
// event funtions
void buck_ui_event_ButtonReturn5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&buck_ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &buck_ui_Screen1_screen_init);
        _ui_screen_delete(&buck_ui_Screen6);
    }
}

void buck_ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_label_set_property(buck_ui_LabelTypeLoad, _UI_LABEL_PROPERTY_TEXT, "Resistiva");
        resistive_load(e);
    }
}

void buck_ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_label_set_property(buck_ui_LabelTypeLoad, _UI_LABEL_PROPERTY_TEXT, "Inductiva");
        inductive_load(e);
    }
}

// build funtions

void buck_ui_Screen6_screen_init(void)
{
    buck_ui_Screen6 = lv_obj_create(NULL);
    lv_obj_remove_flag(buck_ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    buck_ui_ButtonReturn5 = lv_button_create(buck_ui_Screen6);
    lv_obj_set_width(buck_ui_ButtonReturn5, 45);
    lv_obj_set_height(buck_ui_ButtonReturn5, 40);
    lv_obj_add_flag(buck_ui_ButtonReturn5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(buck_ui_ButtonReturn5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(buck_ui_ButtonReturn5, &buck_ui_img_images_arrow_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    buck_ui_Panel4 = lv_obj_create(buck_ui_Screen6);
    lv_obj_set_width(buck_ui_Panel4, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(buck_ui_Panel4, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(buck_ui_Panel4, -4);
    lv_obj_set_y(buck_ui_Panel4, -68);
    lv_obj_set_align(buck_ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(buck_ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(buck_ui_Panel4, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(buck_ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    buck_ui_Label16 = lv_label_create(buck_ui_Panel4);
    lv_obj_set_width(buck_ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(buck_ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(buck_ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(buck_ui_Label16, "Elegir carga");
    lv_obj_set_style_text_align(buck_ui_Label16, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(buck_ui_Label16, &buck_ui_font_fontMontserratM14Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    buck_ui_Button5 = lv_button_create(buck_ui_Screen6);
    lv_obj_set_width(buck_ui_Button5, 110);
    lv_obj_set_height(buck_ui_Button5, 50);
    lv_obj_set_x(buck_ui_Button5, 5);
    lv_obj_set_y(buck_ui_Button5, 150);
    lv_obj_add_flag(buck_ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(buck_ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    buck_ui_Label17 = lv_label_create(buck_ui_Button5);
    lv_obj_set_width(buck_ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(buck_ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(buck_ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(buck_ui_Label17, "Resistiva");
    lv_obj_set_style_text_font(buck_ui_Label17, &buck_ui_font_fontMontserratM14Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    buck_ui_Button6 = lv_button_create(buck_ui_Screen6);
    lv_obj_set_width(buck_ui_Button6, 110);
    lv_obj_set_height(buck_ui_Button6, 50);
    lv_obj_set_x(buck_ui_Button6, 125);
    lv_obj_set_y(buck_ui_Button6, 150);
    lv_obj_add_flag(buck_ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(buck_ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    buck_ui_Label18 = lv_label_create(buck_ui_Button6);
    lv_obj_set_width(buck_ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(buck_ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(buck_ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(buck_ui_Label18, "Inductiva");
    lv_obj_set_style_text_align(buck_ui_Label18, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(buck_ui_Label18, &buck_ui_font_fontMontserratM14Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    buck_ui_Label13 = lv_label_create(buck_ui_Screen6);
    lv_obj_set_width(buck_ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(buck_ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(buck_ui_Label13, -50);
    lv_obj_set_y(buck_ui_Label13, 94);
    lv_obj_set_align(buck_ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(buck_ui_Label13, "Carga Activa:");
    lv_obj_set_style_text_align(buck_ui_Label13, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(buck_ui_Label13, &buck_ui_font_fontMontserratM14Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    buck_ui_LabelTypeLoad = lv_label_create(buck_ui_Screen6);
    lv_obj_set_width(buck_ui_LabelTypeLoad, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(buck_ui_LabelTypeLoad, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(buck_ui_LabelTypeLoad, 46);
    lv_obj_set_y(buck_ui_LabelTypeLoad, 94);
    lv_obj_set_align(buck_ui_LabelTypeLoad, LV_ALIGN_CENTER);
    lv_label_set_text(buck_ui_LabelTypeLoad, "Resistiva");
    lv_obj_set_style_text_align(buck_ui_LabelTypeLoad, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(buck_ui_LabelTypeLoad, &buck_ui_font_fontMontserratM14Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(buck_ui_ButtonReturn5, buck_ui_event_ButtonReturn5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(buck_ui_Button5, buck_ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(buck_ui_Button6, buck_ui_event_Button6, LV_EVENT_ALL, NULL);

}

void buck_ui_Screen6_screen_destroy(void)
{
    if(buck_ui_Screen6) lv_obj_del(buck_ui_Screen6);

    // NULL screen variables
    buck_ui_Screen6 = NULL;
    buck_ui_ButtonReturn5 = NULL;
    buck_ui_Panel4 = NULL;
    buck_ui_Label16 = NULL;
    buck_ui_Button5 = NULL;
    buck_ui_Label17 = NULL;
    buck_ui_Button6 = NULL;
    buck_ui_Label18 = NULL;
    buck_ui_Label13 = NULL;
    buck_ui_LabelTypeLoad = NULL;

}
