// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: buck_UI

#include "buck_ui.h"

lv_obj_t * buck_ui_Screen5 = NULL;
lv_obj_t * buck_ui_ButtonReturn4 = NULL;
lv_obj_t * buck_ui_Panel3 = NULL;
lv_obj_t * buck_ui_Label11 = NULL;
lv_obj_t * buck_ui_SliderSP = NULL;
lv_obj_t * buck_ui_setPointValue = NULL;
lv_obj_t * buck_ui_ButtonReturnDefault3 = NULL;
lv_obj_t * buck_ui_Label12 = NULL;
// event funtions
void buck_ui_event_ButtonReturn4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&buck_ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &buck_ui_Screen3_screen_init);
        _ui_screen_delete(&buck_ui_Screen5);
    }
}

void buck_ui_event_SliderSP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(buck_ui_setPointValue, target, "", " V");
    }
}

void buck_ui_event_ButtonReturnDefault3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_slider_set_property(buck_ui_SliderSP, _UI_SLIDER_PROPERTY_VALUE_WITH_ANIM, 6);
        _ui_label_set_property(buck_ui_setPointValue, _UI_LABEL_PROPERTY_TEXT, "6 V");
    }
}

// build funtions

void buck_ui_Screen5_screen_init(void)
{
    buck_ui_Screen5 = lv_obj_create(NULL);
    lv_obj_remove_flag(buck_ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    buck_ui_ButtonReturn4 = lv_button_create(buck_ui_Screen5);
    lv_obj_set_width(buck_ui_ButtonReturn4, 45);
    lv_obj_set_height(buck_ui_ButtonReturn4, 40);
    lv_obj_add_flag(buck_ui_ButtonReturn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(buck_ui_ButtonReturn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(buck_ui_ButtonReturn4, &buck_ui_img_images_arrow_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    buck_ui_Panel3 = lv_obj_create(buck_ui_Screen5);
    lv_obj_set_width(buck_ui_Panel3, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(buck_ui_Panel3, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(buck_ui_Panel3, 0);
    lv_obj_set_y(buck_ui_Panel3, -60);
    lv_obj_set_align(buck_ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(buck_ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(buck_ui_Panel3, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(buck_ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    buck_ui_Label11 = lv_label_create(buck_ui_Panel3);
    lv_obj_set_width(buck_ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(buck_ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(buck_ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(buck_ui_Label11, "Ajuste de Control PID");
    lv_obj_set_style_text_align(buck_ui_Label11, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(buck_ui_Label11, &buck_ui_font_fontMontserratM14Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    buck_ui_SliderSP = lv_slider_create(buck_ui_Screen5);
    lv_slider_set_range(buck_ui_SliderSP, 0, 12);
    lv_slider_set_value(buck_ui_SliderSP, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(buck_ui_SliderSP) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(buck_ui_SliderSP, 0, LV_ANIM_OFF);
    lv_obj_set_width(buck_ui_SliderSP, 150);
    lv_obj_set_height(buck_ui_SliderSP, 10);
    lv_obj_set_x(buck_ui_SliderSP, 0);
    lv_obj_set_y(buck_ui_SliderSP, 20);
    lv_obj_set_align(buck_ui_SliderSP, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(buck_ui_SliderSP, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(buck_ui_SliderSP,
                                                                                               lv_obj_get_style_pad_right(buck_ui_SliderSP, LV_PART_MAIN) + 1, LV_PART_MAIN);
    buck_ui_setPointValue = lv_label_create(buck_ui_Screen5);
    lv_obj_set_width(buck_ui_setPointValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(buck_ui_setPointValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(buck_ui_setPointValue, LV_ALIGN_CENTER);
    lv_label_set_text(buck_ui_setPointValue, "0 V");
    lv_obj_set_style_text_align(buck_ui_setPointValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(buck_ui_setPointValue, &buck_ui_font_fontMontserratM14Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    buck_ui_ButtonReturnDefault3 = lv_button_create(buck_ui_Screen5);
    lv_obj_set_width(buck_ui_ButtonReturnDefault3, 100);
    lv_obj_set_height(buck_ui_ButtonReturnDefault3, 50);
    lv_obj_set_x(buck_ui_ButtonReturnDefault3, 0);
    lv_obj_set_y(buck_ui_ButtonReturnDefault3, 90);
    lv_obj_set_align(buck_ui_ButtonReturnDefault3, LV_ALIGN_CENTER);
    lv_obj_add_flag(buck_ui_ButtonReturnDefault3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(buck_ui_ButtonReturnDefault3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    buck_ui_Label12 = lv_label_create(buck_ui_ButtonReturnDefault3);
    lv_obj_set_width(buck_ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(buck_ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(buck_ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(buck_ui_Label12, "Valor por\ndefecto");
    lv_obj_set_style_text_align(buck_ui_Label12, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(buck_ui_Label12, &buck_ui_font_fontMontserratM14Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(buck_ui_ButtonReturn4, buck_ui_event_ButtonReturn4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(buck_ui_SliderSP, buck_ui_event_SliderSP, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(buck_ui_ButtonReturnDefault3, buck_ui_event_ButtonReturnDefault3, LV_EVENT_ALL, NULL);

}

void buck_ui_Screen5_screen_destroy(void)
{
    if(buck_ui_Screen5) lv_obj_del(buck_ui_Screen5);

    // NULL screen variables
    buck_ui_Screen5 = NULL;
    buck_ui_ButtonReturn4 = NULL;
    buck_ui_Panel3 = NULL;
    buck_ui_Label11 = NULL;
    buck_ui_SliderSP = NULL;
    buck_ui_setPointValue = NULL;
    buck_ui_ButtonReturnDefault3 = NULL;
    buck_ui_Label12 = NULL;

}
