// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: buck_UI

#include "buck_ui.h"
#include "buck_ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * buck_ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void buck_ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    buck_ui_Screen1_screen_init();
    buck_ui_Screen2_screen_init();
    buck_ui_Screen3_screen_init();
    buck_ui_Screen4_screen_init();
    buck_ui_Screen5_screen_init();
    buck_ui_Screen6_screen_init();
    buck_ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(buck_ui_Screen1);
}

void buck_ui_destroy(void)
{
    buck_ui_Screen1_screen_destroy();
    buck_ui_Screen2_screen_destroy();
    buck_ui_Screen3_screen_destroy();
    buck_ui_Screen4_screen_destroy();
    buck_ui_Screen5_screen_destroy();
    buck_ui_Screen6_screen_destroy();
}
