// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: buck_UI

#ifndef BUCK_UI_SCREEN3_H
#define BUCK_UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: buck_ui_Screen3
extern void buck_ui_Screen3_screen_init(void);
extern void buck_ui_Screen3_screen_destroy(void);
extern lv_obj_t * buck_ui_Screen3;
extern void buck_ui_event_ButtonReturn2(lv_event_t * e);
extern lv_obj_t * buck_ui_ButtonReturn2;
extern void buck_ui_event_ButtonPWM(lv_event_t * e);
extern lv_obj_t * buck_ui_ButtonPWM;
extern lv_obj_t * buck_ui_Label7;
extern void buck_ui_event_ButtonPID(lv_event_t * e);
extern lv_obj_t * buck_ui_ButtonPID;
extern lv_obj_t * buck_ui_Label8;
// CUSTOM VARIABLES
extern lv_obj_t * buck_ui_buck_ButtonReturn2;
extern lv_obj_t * buck_ui_buck_ButtonPWM;
extern lv_obj_t * buck_ui_buck_ButtonPID;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

