// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: buck_UI

#include "buck_ui.h"

lv_obj_t * buck_ui_buck_loadScreen;
lv_obj_t * buck_ui_buck_controlScreen;
lv_obj_t * buck_ui_buck_freqScreen;
lv_obj_t * buck_ui_Screen1 = NULL;
lv_obj_t * buck_ui_freqScreen = NULL;
lv_obj_t * buck_ui_Label1 = NULL;
lv_obj_t * buck_ui_controlScreen = NULL;
lv_obj_t * buck_ui_Label2 = NULL;
lv_obj_t * buck_ui_loadScreen = NULL;
lv_obj_t * buck_ui_Label3 = NULL;
lv_obj_t * buck_ui_Image1 = NULL;
lv_obj_t * buck_ui_Label4 = NULL;
// event funtions
void buck_ui_event_freqScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&buck_ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &buck_ui_Screen2_screen_init);
        _ui_screen_delete(&buck_ui_Screen1);
    }
}

void buck_ui_event_controlScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&buck_ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &buck_ui_Screen3_screen_init);
        _ui_screen_delete(&buck_ui_Screen1);
    }
}

void buck_ui_event_loadScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&buck_ui_Screen6, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &buck_ui_Screen6_screen_init);
        _ui_screen_delete(&buck_ui_Screen1);
    }
}

// build funtions

void buck_ui_Screen1_screen_init(void)
{
    buck_ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(buck_ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    buck_ui_freqScreen = lv_button_create(buck_ui_Screen1);
    lv_obj_set_width(buck_ui_freqScreen, 110);
    lv_obj_set_height(buck_ui_freqScreen, 60);
    lv_obj_set_x(buck_ui_freqScreen, 5);
    lv_obj_set_y(buck_ui_freqScreen, 80);
    lv_obj_add_flag(buck_ui_freqScreen, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(buck_ui_freqScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    buck_ui_Label1 = lv_label_create(buck_ui_freqScreen);
    lv_obj_set_width(buck_ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(buck_ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(buck_ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(buck_ui_Label1, "Frecuencia de\nconmutación");
    lv_obj_set_style_text_align(buck_ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(buck_ui_Label1, &buck_ui_font_fontRobotoBold16Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    buck_ui_controlScreen = lv_button_create(buck_ui_Screen1);
    lv_obj_set_width(buck_ui_controlScreen, 110);
    lv_obj_set_height(buck_ui_controlScreen, 60);
    lv_obj_set_x(buck_ui_controlScreen, 125);
    lv_obj_set_y(buck_ui_controlScreen, 80);
    lv_obj_add_flag(buck_ui_controlScreen, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(buck_ui_controlScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    buck_ui_Label2 = lv_label_create(buck_ui_controlScreen);
    lv_obj_set_width(buck_ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(buck_ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(buck_ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(buck_ui_Label2, "Control");
    lv_obj_set_style_text_font(buck_ui_Label2, &buck_ui_font_fontRobotoBold16Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    buck_ui_loadScreen = lv_button_create(buck_ui_Screen1);
    lv_obj_set_width(buck_ui_loadScreen, 110);
    lv_obj_set_height(buck_ui_loadScreen, 60);
    lv_obj_set_x(buck_ui_loadScreen, 5);
    lv_obj_set_y(buck_ui_loadScreen, 150);
    lv_obj_add_flag(buck_ui_loadScreen, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(buck_ui_loadScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    buck_ui_Label3 = lv_label_create(buck_ui_loadScreen);
    lv_obj_set_width(buck_ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(buck_ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(buck_ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(buck_ui_Label3, "Carga");
    lv_obj_set_style_text_font(buck_ui_Label3, &buck_ui_font_fontRobotoBold16Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    buck_ui_Image1 = lv_image_create(buck_ui_Screen1);
    lv_image_set_src(buck_ui_Image1, &buck_ui_img_images_buck_png);
    lv_obj_set_width(buck_ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(buck_ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(buck_ui_Image1, 0);
    lv_obj_set_y(buck_ui_Image1, 100);
    lv_obj_set_align(buck_ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(buck_ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(buck_ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(buck_ui_Image1, 140);

    buck_ui_Label4 = lv_label_create(buck_ui_Screen1);
    lv_obj_set_width(buck_ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(buck_ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(buck_ui_Label4, 0);
    lv_obj_set_y(buck_ui_Label4, -110);
    lv_obj_set_align(buck_ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(buck_ui_Label4, "Módulo convertidor\nreductor o Buck");
    lv_obj_set_style_text_align(buck_ui_Label4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(buck_ui_Label4, &buck_ui_font_fontRobotoBold18Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(buck_ui_freqScreen, buck_ui_event_freqScreen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(buck_ui_controlScreen, buck_ui_event_controlScreen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(buck_ui_loadScreen, buck_ui_event_loadScreen, LV_EVENT_ALL, NULL);
    buck_ui_buck_freqScreen = buck_ui_freqScreen;
    buck_ui_buck_controlScreen = buck_ui_controlScreen;
    buck_ui_buck_loadScreen = buck_ui_loadScreen;

}

void buck_ui_Screen1_screen_destroy(void)
{
    if(buck_ui_Screen1) lv_obj_del(buck_ui_Screen1);

    // NULL screen variables
    buck_ui_Screen1 = NULL;
    buck_ui_buck_freqScreen = NULL;
    buck_ui_freqScreen = NULL;
    buck_ui_Label1 = NULL;
    buck_ui_buck_controlScreen = NULL;
    buck_ui_controlScreen = NULL;
    buck_ui_Label2 = NULL;
    buck_ui_buck_loadScreen = NULL;
    buck_ui_loadScreen = NULL;
    buck_ui_Label3 = NULL;
    buck_ui_Image1 = NULL;
    buck_ui_Label4 = NULL;

}
