// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: buck_UI

#include "buck_ui.h"

lv_obj_t * buck_ui_Screen4 = NULL;
lv_obj_t * buck_ui_ButtonReturn3 = NULL;
lv_obj_t * buck_ui_Panel2 = NULL;
lv_obj_t * buck_ui_Label9 = NULL;
lv_obj_t * buck_ui_SliderDuty = NULL;
lv_obj_t * buck_ui_dutyPercentage = NULL;
lv_obj_t * buck_ui_ButtonReturnDefault2 = NULL;
lv_obj_t * buck_ui_Label10 = NULL;
// event funtions
void buck_ui_event_ButtonReturn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&buck_ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &buck_ui_Screen3_screen_init);
        _ui_screen_delete(&buck_ui_Screen4);
    }
}

void buck_ui_event_SliderDuty(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(buck_ui_dutyPercentage, target, "", " %");
    }
}

void buck_ui_event_ButtonReturnDefault2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_slider_set_property(buck_ui_SliderDuty, _UI_SLIDER_PROPERTY_VALUE_WITH_ANIM, 55);
        _ui_label_set_property(buck_ui_dutyPercentage, _UI_LABEL_PROPERTY_TEXT, "55 %");
    }
}

// build funtions

void buck_ui_Screen4_screen_init(void)
{
    buck_ui_Screen4 = lv_obj_create(NULL);
    lv_obj_remove_flag(buck_ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    buck_ui_ButtonReturn3 = lv_button_create(buck_ui_Screen4);
    lv_obj_set_width(buck_ui_ButtonReturn3, 45);
    lv_obj_set_height(buck_ui_ButtonReturn3, 40);
    lv_obj_add_flag(buck_ui_ButtonReturn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(buck_ui_ButtonReturn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(buck_ui_ButtonReturn3, &buck_ui_img_images_arrow_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    buck_ui_Panel2 = lv_obj_create(buck_ui_Screen4);
    lv_obj_set_width(buck_ui_Panel2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(buck_ui_Panel2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(buck_ui_Panel2, 0);
    lv_obj_set_y(buck_ui_Panel2, -60);
    lv_obj_set_align(buck_ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(buck_ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(buck_ui_Panel2, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(buck_ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    buck_ui_Label9 = lv_label_create(buck_ui_Panel2);
    lv_obj_set_width(buck_ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(buck_ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(buck_ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(buck_ui_Label9, "Ajuste de Ciclo de Trabajo");
    lv_obj_set_style_text_align(buck_ui_Label9, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(buck_ui_Label9, &buck_ui_font_fontMontserratM14Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    buck_ui_SliderDuty = lv_slider_create(buck_ui_Screen4);
    lv_slider_set_value(buck_ui_SliderDuty, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(buck_ui_SliderDuty) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(buck_ui_SliderDuty, 0, LV_ANIM_OFF);
    lv_obj_set_width(buck_ui_SliderDuty, 150);
    lv_obj_set_height(buck_ui_SliderDuty, 10);
    lv_obj_set_x(buck_ui_SliderDuty, 0);
    lv_obj_set_y(buck_ui_SliderDuty, 20);
    lv_obj_set_align(buck_ui_SliderDuty, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(buck_ui_SliderDuty, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(buck_ui_SliderDuty,
                                                                                                 lv_obj_get_style_pad_right(buck_ui_SliderDuty, LV_PART_MAIN) + 1, LV_PART_MAIN);
    buck_ui_dutyPercentage = lv_label_create(buck_ui_Screen4);
    lv_obj_set_width(buck_ui_dutyPercentage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(buck_ui_dutyPercentage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(buck_ui_dutyPercentage, LV_ALIGN_CENTER);
    lv_label_set_text(buck_ui_dutyPercentage, "0 %");
    lv_obj_set_style_text_align(buck_ui_dutyPercentage, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(buck_ui_dutyPercentage, &buck_ui_font_fontMontserratM14Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    buck_ui_ButtonReturnDefault2 = lv_button_create(buck_ui_Screen4);
    lv_obj_set_width(buck_ui_ButtonReturnDefault2, 100);
    lv_obj_set_height(buck_ui_ButtonReturnDefault2, 50);
    lv_obj_set_x(buck_ui_ButtonReturnDefault2, 0);
    lv_obj_set_y(buck_ui_ButtonReturnDefault2, 90);
    lv_obj_set_align(buck_ui_ButtonReturnDefault2, LV_ALIGN_CENTER);
    lv_obj_add_flag(buck_ui_ButtonReturnDefault2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(buck_ui_ButtonReturnDefault2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    buck_ui_Label10 = lv_label_create(buck_ui_ButtonReturnDefault2);
    lv_obj_set_width(buck_ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(buck_ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(buck_ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(buck_ui_Label10, "Valor por\ndefecto");
    lv_obj_set_style_text_align(buck_ui_Label10, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(buck_ui_Label10, &buck_ui_font_fontMontserratM14Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(buck_ui_ButtonReturn3, buck_ui_event_ButtonReturn3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(buck_ui_SliderDuty, buck_ui_event_SliderDuty, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(buck_ui_ButtonReturnDefault2, buck_ui_event_ButtonReturnDefault2, LV_EVENT_ALL, NULL);

}

void buck_ui_Screen4_screen_destroy(void)
{
    if(buck_ui_Screen4) lv_obj_del(buck_ui_Screen4);

    // NULL screen variables
    buck_ui_Screen4 = NULL;
    buck_ui_ButtonReturn3 = NULL;
    buck_ui_Panel2 = NULL;
    buck_ui_Label9 = NULL;
    buck_ui_SliderDuty = NULL;
    buck_ui_dutyPercentage = NULL;
    buck_ui_ButtonReturnDefault2 = NULL;
    buck_ui_Label10 = NULL;

}
