// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: buck_UI

#ifndef BUCK_UI_SCREEN4_H
#define BUCK_UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: buck_ui_Screen4
extern void buck_ui_Screen4_screen_init(void);
extern void buck_ui_Screen4_screen_destroy(void);
extern lv_obj_t * buck_ui_Screen4;
extern void buck_ui_event_ButtonReturn3(lv_event_t * e);
extern lv_obj_t * buck_ui_ButtonReturn3;
extern lv_obj_t * buck_ui_Panel2;
extern lv_obj_t * buck_ui_Label9;
extern void buck_ui_event_SliderDuty(lv_event_t * e);
extern lv_obj_t * buck_ui_SliderDuty;
extern lv_obj_t * buck_ui_dutyPercentage;
extern void buck_ui_event_ButtonReturnDefault2(lv_event_t * e);
extern lv_obj_t * buck_ui_ButtonReturnDefault2;
extern lv_obj_t * buck_ui_Label10;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

