// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: buck_UI

#ifndef BUCK_UI_H
#define BUCK_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "buck_ui_helpers.h"
#include "buck_ui_events.h"

///////////////////// SCREENS ////////////////////

#include "buck_ui_Screen1.h"
#include "buck_ui_Screen2.h"
#include "buck_ui_Screen3.h"
#include "buck_ui_Screen4.h"
#include "buck_ui_Screen5.h"
#include "buck_ui_Screen6.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * buck_ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(buck_ui_img_images_buck_png);    // assets/images/buck.png
LV_IMG_DECLARE(buck_ui_img_images_arrow_png);    // assets/images/arrow.png

// FONTS
LV_FONT_DECLARE(buck_ui_font_fontMontserratM14Tildes);
LV_FONT_DECLARE(buck_ui_font_fontMontserratM16Tildes);
LV_FONT_DECLARE(buck_ui_font_fontMontserratM18Tildes);

// UI INIT
void buck_ui_init(void);
void buck_ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
