// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: buck_UI

#include "buck_ui.h"

lv_obj_t * buck_ui_buck_ButtonReturnDefault1;
lv_obj_t * buck_ui_buck_SliderFreq1;
lv_obj_t * buck_ui_buck_ButtonReturn1;
lv_obj_t * buck_ui_Screen2 = NULL;
lv_obj_t * buck_ui_ButtonReturn1 = NULL;
lv_obj_t * buck_ui_Panel1 = NULL;
lv_obj_t * buck_ui_Label5 = NULL;
lv_obj_t * buck_ui_SliderFreq1 = NULL;
lv_obj_t * buck_ui_freqValue = NULL;
lv_obj_t * buck_ui_ButtonReturnDefault1 = NULL;
lv_obj_t * buck_ui_Label6 = NULL;
// event funtions
void buck_ui_event_ButtonReturn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&buck_ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &buck_ui_Screen1_screen_init);
        _ui_screen_delete(&buck_ui_Screen2);
    }
}

void buck_ui_event_SliderFreq1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(buck_ui_freqValue, target, "", " kHz");
    }
}

void buck_ui_event_ButtonReturnDefault1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_slider_set_property(buck_ui_SliderFreq1, _UI_SLIDER_PROPERTY_VALUE_WITH_ANIM, 19);
        _ui_label_set_property(buck_ui_freqValue, _UI_LABEL_PROPERTY_TEXT, "19 kHz");
    }
}

// build funtions

void buck_ui_Screen2_screen_init(void)
{
    buck_ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(buck_ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    buck_ui_ButtonReturn1 = lv_button_create(buck_ui_Screen2);
    lv_obj_set_width(buck_ui_ButtonReturn1, 45);
    lv_obj_set_height(buck_ui_ButtonReturn1, 40);
    lv_obj_add_flag(buck_ui_ButtonReturn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(buck_ui_ButtonReturn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(buck_ui_ButtonReturn1, &buck_ui_img_images_arrow_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    buck_ui_Panel1 = lv_obj_create(buck_ui_Screen2);
    lv_obj_set_width(buck_ui_Panel1, LV_SIZE_CONTENT);   /// 170
    lv_obj_set_height(buck_ui_Panel1, LV_SIZE_CONTENT);    /// 60
    lv_obj_set_x(buck_ui_Panel1, 0);
    lv_obj_set_y(buck_ui_Panel1, -60);
    lv_obj_set_align(buck_ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(buck_ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(buck_ui_Panel1, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(buck_ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    buck_ui_Label5 = lv_label_create(buck_ui_Panel1);
    lv_obj_set_width(buck_ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(buck_ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(buck_ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(buck_ui_Label5, "Ajuste de frecuencia\nde conmutación");
    lv_obj_set_style_text_align(buck_ui_Label5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(buck_ui_Label5, &buck_ui_font_fontRobotoBold18Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    buck_ui_SliderFreq1 = lv_slider_create(buck_ui_Screen2);
    lv_slider_set_range(buck_ui_SliderFreq1, 1, 19);
    lv_slider_set_value(buck_ui_SliderFreq1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(buck_ui_SliderFreq1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(buck_ui_SliderFreq1, 0, LV_ANIM_OFF);
    lv_obj_set_width(buck_ui_SliderFreq1, 150);
    lv_obj_set_height(buck_ui_SliderFreq1, 10);
    lv_obj_set_x(buck_ui_SliderFreq1, 0);
    lv_obj_set_y(buck_ui_SliderFreq1, 30);
    lv_obj_set_align(buck_ui_SliderFreq1, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(buck_ui_SliderFreq1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(buck_ui_SliderFreq1,
                                                                                                  lv_obj_get_style_pad_right(buck_ui_SliderFreq1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    buck_ui_freqValue = lv_label_create(buck_ui_Screen2);
    lv_obj_set_width(buck_ui_freqValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(buck_ui_freqValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(buck_ui_freqValue, LV_ALIGN_CENTER);
    lv_label_set_text(buck_ui_freqValue, "1 kHz");
    lv_obj_set_style_text_font(buck_ui_freqValue, &buck_ui_font_fontRobotoRegular14Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    buck_ui_ButtonReturnDefault1 = lv_button_create(buck_ui_Screen2);
    lv_obj_set_width(buck_ui_ButtonReturnDefault1, 100);
    lv_obj_set_height(buck_ui_ButtonReturnDefault1, 50);
    lv_obj_set_x(buck_ui_ButtonReturnDefault1, 0);
    lv_obj_set_y(buck_ui_ButtonReturnDefault1, 90);
    lv_obj_set_align(buck_ui_ButtonReturnDefault1, LV_ALIGN_CENTER);
    lv_obj_add_flag(buck_ui_ButtonReturnDefault1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(buck_ui_ButtonReturnDefault1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    buck_ui_Label6 = lv_label_create(buck_ui_ButtonReturnDefault1);
    lv_obj_set_width(buck_ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(buck_ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(buck_ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(buck_ui_Label6, "Valor por\ndefecto");
    lv_obj_set_style_text_align(buck_ui_Label6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(buck_ui_Label6, &buck_ui_font_fontRobotoBold16Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(buck_ui_ButtonReturn1, buck_ui_event_ButtonReturn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(buck_ui_SliderFreq1, buck_ui_event_SliderFreq1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(buck_ui_ButtonReturnDefault1, buck_ui_event_ButtonReturnDefault1, LV_EVENT_ALL, NULL);
    buck_ui_buck_ButtonReturn1 = buck_ui_ButtonReturn1;
    buck_ui_buck_SliderFreq1 = buck_ui_SliderFreq1;
    buck_ui_buck_ButtonReturnDefault1 = buck_ui_ButtonReturnDefault1;

}

void buck_ui_Screen2_screen_destroy(void)
{
    if(buck_ui_Screen2) lv_obj_del(buck_ui_Screen2);

    // NULL screen variables
    buck_ui_Screen2 = NULL;
    buck_ui_buck_ButtonReturn1 = NULL;
    buck_ui_ButtonReturn1 = NULL;
    buck_ui_Panel1 = NULL;
    buck_ui_Label5 = NULL;
    buck_ui_buck_SliderFreq1 = NULL;
    buck_ui_SliderFreq1 = NULL;
    buck_ui_freqValue = NULL;
    buck_ui_buck_ButtonReturnDefault1 = NULL;
    buck_ui_ButtonReturnDefault1 = NULL;
    buck_ui_Label6 = NULL;

}
