// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: buck_UI

#ifndef BUCK_UI_SCREEN6_H
#define BUCK_UI_SCREEN6_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: buck_ui_Screen6
extern void buck_ui_Screen6_screen_init(void);
extern void buck_ui_Screen6_screen_destroy(void);
extern lv_obj_t * buck_ui_Screen6;
extern void buck_ui_event_ButtonReturn5(lv_event_t * e);
extern lv_obj_t * buck_ui_ButtonReturn5;
extern lv_obj_t * buck_ui_Panel4;
extern lv_obj_t * buck_ui_Label16;
extern void buck_ui_event_Button5(lv_event_t * e);
extern lv_obj_t * buck_ui_Button5;
extern lv_obj_t * buck_ui_Label17;
extern void buck_ui_event_Button6(lv_event_t * e);
extern lv_obj_t * buck_ui_Button6;
extern lv_obj_t * buck_ui_Label18;
extern lv_obj_t * buck_ui_Label13;
extern lv_obj_t * buck_ui_LabelTypeLoad;
// CUSTOM VARIABLES
extern lv_obj_t * buck_ui_buck_ButtonReturn5;
extern lv_obj_t * buck_ui_buck_Button5;
extern lv_obj_t * buck_ui_buck_Button6;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

