// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: buck_UI

#ifndef BUCK_UI_SCREEN1_H
#define BUCK_UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: buck_ui_Screen1
extern void buck_ui_Screen1_screen_init(void);
extern void buck_ui_Screen1_screen_destroy(void);
extern lv_obj_t * buck_ui_Screen1;
extern void buck_ui_event_freqScreen(lv_event_t * e);
extern lv_obj_t * buck_ui_freqScreen;
extern lv_obj_t * buck_ui_Label1;
extern void buck_ui_event_controlScreen(lv_event_t * e);
extern lv_obj_t * buck_ui_controlScreen;
extern lv_obj_t * buck_ui_Label2;
extern void buck_ui_event_loadScreen(lv_event_t * e);
extern lv_obj_t * buck_ui_loadScreen;
extern lv_obj_t * buck_ui_Label3;
extern lv_obj_t * buck_ui_Image1;
extern lv_obj_t * buck_ui_Label4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

