// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: buck_UI

#ifndef BUCK_UI_SCREEN2_H
#define BUCK_UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: buck_ui_Screen2
extern void buck_ui_Screen2_screen_init(void);
extern void buck_ui_Screen2_screen_destroy(void);
extern lv_obj_t * buck_ui_Screen2;
extern void buck_ui_event_ButtonReturn1(lv_event_t * e);
extern lv_obj_t * buck_ui_ButtonReturn1;
extern lv_obj_t * buck_ui_Panel1;
extern lv_obj_t * buck_ui_Label5;
extern void buck_ui_event_SliderFreq1(lv_event_t * e);
extern lv_obj_t * buck_ui_SliderFreq1;
extern lv_obj_t * buck_ui_freqValue;
extern void buck_ui_event_ButtonReturnDefault1(lv_event_t * e);
extern lv_obj_t * buck_ui_ButtonReturnDefault1;
extern lv_obj_t * buck_ui_Label6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

