// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: buck_UI

#include "buck_ui.h"

lv_obj_t * buck_ui_buck_ButtonPID;
lv_obj_t * buck_ui_buck_ButtonPWM;
lv_obj_t * buck_ui_buck_ButtonReturn2;
lv_obj_t * buck_ui_Screen3 = NULL;
lv_obj_t * buck_ui_ButtonReturn2 = NULL;
lv_obj_t * buck_ui_ButtonPWM = NULL;
lv_obj_t * buck_ui_Label7 = NULL;
lv_obj_t * buck_ui_ButtonPID = NULL;
lv_obj_t * buck_ui_Label8 = NULL;
// event funtions
void buck_ui_event_ButtonReturn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&buck_ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &buck_ui_Screen1_screen_init);
        _ui_screen_delete(&buck_ui_Screen3);
    }
}

void buck_ui_event_ButtonPWM(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&buck_ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &buck_ui_Screen4_screen_init);
        _ui_screen_delete(&buck_ui_Screen3);
    }
    if(event_code == LV_EVENT_PRESSED) {
        controlFixedPWM(e);
    }
}

void buck_ui_event_ButtonPID(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&buck_ui_Screen5, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &buck_ui_Screen5_screen_init);
        _ui_screen_delete(&buck_ui_Screen3);
    }
    if(event_code == LV_EVENT_PRESSED) {
        controlPID(e);
    }
}

// build funtions

void buck_ui_Screen3_screen_init(void)
{
    buck_ui_Screen3 = lv_obj_create(NULL);
    lv_obj_remove_flag(buck_ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    buck_ui_ButtonReturn2 = lv_button_create(buck_ui_Screen3);
    lv_obj_set_width(buck_ui_ButtonReturn2, 45);
    lv_obj_set_height(buck_ui_ButtonReturn2, 40);
    lv_obj_add_flag(buck_ui_ButtonReturn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(buck_ui_ButtonReturn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(buck_ui_ButtonReturn2, &buck_ui_img_images_arrow_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    buck_ui_ButtonPWM = lv_button_create(buck_ui_Screen3);
    lv_obj_set_width(buck_ui_ButtonPWM, 100);
    lv_obj_set_height(buck_ui_ButtonPWM, 50);
    lv_obj_set_x(buck_ui_ButtonPWM, 0);
    lv_obj_set_y(buck_ui_ButtonPWM, -50);
    lv_obj_set_align(buck_ui_ButtonPWM, LV_ALIGN_CENTER);
    lv_obj_add_flag(buck_ui_ButtonPWM, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(buck_ui_ButtonPWM, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    buck_ui_Label7 = lv_label_create(buck_ui_ButtonPWM);
    lv_obj_set_width(buck_ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(buck_ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(buck_ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(buck_ui_Label7, "Control Fijo\nPWM");
    lv_obj_set_style_text_align(buck_ui_Label7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(buck_ui_Label7, &buck_ui_font_fontRobotoBold16Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    buck_ui_ButtonPID = lv_button_create(buck_ui_Screen3);
    lv_obj_set_width(buck_ui_ButtonPID, 100);
    lv_obj_set_height(buck_ui_ButtonPID, 50);
    lv_obj_set_x(buck_ui_ButtonPID, 0);
    lv_obj_set_y(buck_ui_ButtonPID, 40);
    lv_obj_set_align(buck_ui_ButtonPID, LV_ALIGN_CENTER);
    lv_obj_add_flag(buck_ui_ButtonPID, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(buck_ui_ButtonPID, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    buck_ui_Label8 = lv_label_create(buck_ui_ButtonPID);
    lv_obj_set_width(buck_ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(buck_ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(buck_ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(buck_ui_Label8, "Control PID");
    lv_obj_set_style_text_align(buck_ui_Label8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(buck_ui_Label8, &buck_ui_font_fontRobotoBold16Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(buck_ui_ButtonReturn2, buck_ui_event_ButtonReturn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(buck_ui_ButtonPWM, buck_ui_event_ButtonPWM, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(buck_ui_ButtonPID, buck_ui_event_ButtonPID, LV_EVENT_ALL, NULL);
    buck_ui_buck_ButtonReturn2 = buck_ui_ButtonReturn2;
    buck_ui_buck_ButtonPWM = buck_ui_ButtonPWM;
    buck_ui_buck_ButtonPID = buck_ui_ButtonPID;

}

void buck_ui_Screen3_screen_destroy(void)
{
    if(buck_ui_Screen3) lv_obj_del(buck_ui_Screen3);

    // NULL screen variables
    buck_ui_Screen3 = NULL;
    buck_ui_buck_ButtonReturn2 = NULL;
    buck_ui_ButtonReturn2 = NULL;
    buck_ui_buck_ButtonPWM = NULL;
    buck_ui_ButtonPWM = NULL;
    buck_ui_Label7 = NULL;
    buck_ui_buck_ButtonPID = NULL;
    buck_ui_ButtonPID = NULL;
    buck_ui_Label8 = NULL;

}
