// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: UI_TFI

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern void ui_event_ButtonReturn1(lv_event_t * e);
extern lv_obj_t * ui_ButtonReturn1;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label9;
extern void ui_event_SliderFreq1(lv_event_t * e);
extern lv_obj_t * ui_SliderFreq1;
extern lv_obj_t * ui_freqValue;
extern void ui_event_ButtonReturnDefault1(lv_event_t * e);
extern lv_obj_t * ui_ButtonReturnDefault1;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

