// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: UI_TFI

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern void ui_event_Function1(lv_event_t * e);
extern lv_obj_t * ui_Function1;
extern lv_obj_t * ui_Label4;
extern void ui_event_Function2(lv_event_t * e);
extern lv_obj_t * ui_Function2;
extern lv_obj_t * ui_Label5;
extern void ui_event_Function3(lv_event_t * e);
extern lv_obj_t * ui_Function3;
extern lv_obj_t * ui_Label6;
extern void ui_event_Function4(lv_event_t * e);
extern lv_obj_t * ui_Function4;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_buckImage;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

