// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: dimmer_UI

#include "ui.h"

void update_time_label(lv_event_t * e)
{
	// Your code here
}

void dimmer_control_analog(lv_event_t * e)
{
	// Your code here
}

void dimmer_control_digital(lv_event_t * e)
{
	// Your code here
}

void dimmer_digital_full_cycle(lv_event_t * e)
{
	// Your code here
}

void dimmer_digital_positive_cycle(lv_event_t * e)
{
	// Your code here
}

void dimmer_digital_negative_cycle(lv_event_t * e)
{
	// Your code here
}
