// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: dimmer_UI

#include "ui.h"

void update_time_label(lv_event_t * e)
{
	// Your code here
}
