// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: dimmer_UI

#include "ui.h"

lv_obj_t * ui_Screen6 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_SliderSN = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_LabelSN = NULL;
lv_obj_t * ui_ButtonReturn5 = NULL;
lv_obj_t * ui_cicloNegativo = NULL;
// event funtions
void ui_event_SliderSN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        update_time_label(e);
    }
}

void ui_event_ButtonReturn5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
        _ui_screen_delete(&ui_Screen6);
    }
}

// build funtions

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label12 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 0);
    lv_obj_set_y(ui_Label12, -100);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Semiciclo Negativo");
    lv_obj_set_style_text_font(ui_Label12, &ui_font_fontRobotoBold18Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderSN = lv_slider_create(ui_Screen6);
    lv_slider_set_range(ui_SliderSN, 0, 50);
    lv_slider_set_value(ui_SliderSN, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderSN) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderSN, 1, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSN, 150);
    lv_obj_set_height(ui_SliderSN, 10);
    lv_obj_set_align(ui_SliderSN, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_SliderSN, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_SliderSN,
                                                                                               lv_obj_get_style_pad_right(ui_SliderSN, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Label13 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 0);
    lv_obj_set_y(ui_Label13, -50);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Tiempo de disparo");
    lv_obj_set_style_text_font(ui_Label13, &ui_font_fontRobotoMedium14Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSN = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_LabelSN, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSN, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSN, 0);
    lv_obj_set_y(ui_LabelSN, -20);
    lv_obj_set_align(ui_LabelSN, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSN, "0 ms");
    lv_obj_set_style_text_font(ui_LabelSN, &ui_font_fontRobotoRegular14Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonReturn5 = lv_button_create(ui_Screen6);
    lv_obj_set_width(ui_ButtonReturn5, 45);
    lv_obj_set_height(ui_ButtonReturn5, 40);
    lv_obj_add_flag(ui_ButtonReturn5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonReturn5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_ButtonReturn5, &ui_img_images_arrow_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_ButtonReturn5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_ButtonReturn5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cicloNegativo = lv_image_create(ui_Screen6);
    lv_image_set_src(ui_cicloNegativo, &ui_img_images_negativo_sf_png);
    lv_obj_set_width(ui_cicloNegativo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cicloNegativo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cicloNegativo, 0);
    lv_obj_set_y(ui_cicloNegativo, 85);
    lv_obj_set_align(ui_cicloNegativo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cicloNegativo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_cicloNegativo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_SliderSN, ui_event_SliderSN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonReturn5, ui_event_ButtonReturn5, LV_EVENT_ALL, NULL);

}

void ui_Screen6_screen_destroy(void)
{
    if(ui_Screen6) lv_obj_del(ui_Screen6);

    // NULL screen variables
    ui_Screen6 = NULL;
    ui_Label12 = NULL;
    ui_SliderSN = NULL;
    ui_Label13 = NULL;
    ui_LabelSN = NULL;
    ui_ButtonReturn5 = NULL;
    ui_cicloNegativo = NULL;

}
