// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: dimmer_UI

#include "ui.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_SliderCC = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_LabelCC = NULL;
lv_obj_t * ui_ButtonReturn3 = NULL;
// event funtions
void ui_event_SliderCC(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        update_time_label(e);
    }
}

void ui_event_ButtonReturn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
        _ui_screen_delete(&ui_Screen4);
    }
}

// build funtions

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 0);
    lv_obj_set_y(ui_Label8, -50);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Ciclo Completo");
    lv_obj_set_style_text_font(ui_Label8, &ui_font_fontRobotoBold18Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderCC = lv_slider_create(ui_Screen4);
    lv_slider_set_range(ui_SliderCC, 0, 50);
    lv_slider_set_value(ui_SliderCC, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderCC) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderCC, 1, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderCC, 150);
    lv_obj_set_height(ui_SliderCC, 10);
    lv_obj_set_x(ui_SliderCC, 2);
    lv_obj_set_y(ui_SliderCC, 50);
    lv_obj_set_align(ui_SliderCC, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_SliderCC, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_SliderCC,
                                                                                               lv_obj_get_style_pad_right(ui_SliderCC, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Label9 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Tiempo de disparo");
    lv_obj_set_style_text_font(ui_Label9, &ui_font_fontRobotoMedium14Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCC = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelCC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCC, 0);
    lv_obj_set_y(ui_LabelCC, 30);
    lv_obj_set_align(ui_LabelCC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCC, "0 ms");
    lv_obj_set_style_text_font(ui_LabelCC, &ui_font_fontRobotoRegular14Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonReturn3 = lv_button_create(ui_Screen4);
    lv_obj_set_width(ui_ButtonReturn3, 45);
    lv_obj_set_height(ui_ButtonReturn3, 40);
    lv_obj_add_flag(ui_ButtonReturn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonReturn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_ButtonReturn3, &ui_img_images_arrow_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_ButtonReturn3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_ButtonReturn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SliderCC, ui_event_SliderCC, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonReturn3, ui_event_ButtonReturn3, LV_EVENT_ALL, NULL);

}

void ui_Screen4_screen_destroy(void)
{
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_Label8 = NULL;
    ui_SliderCC = NULL;
    ui_Label9 = NULL;
    ui_LabelCC = NULL;
    ui_ButtonReturn3 = NULL;

}
