// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: dimmer_UI

#ifndef UI_SCREEN6_H
#define UI_SCREEN6_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen6
extern void ui_Screen6_screen_init(void);
extern void ui_Screen6_screen_destroy(void);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Label12;
extern void ui_event_SliderSN(lv_event_t * e);
extern lv_obj_t * ui_SliderSN;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_LabelSN;
extern void ui_event_ButtonReturn5(lv_event_t * e);
extern lv_obj_t * ui_ButtonReturn5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

