// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: UI_TFI

#include "ui.h"
#include "driver/gpio.h"

void resistive_load(lv_event_t * e)
{
	gpio_set_level(GPIO_NUM_18, 0);

}

void inductive_load(lv_event_t * e)
{
	gpio_set_level(GPIO_NUM_18, 1);
}
