// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: UI_TFI

#include "ui.h"

lv_obj_t * ui_Screen5 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Label18 = NULL;
// event funtions
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
        _ui_screen_delete(&ui_Screen5);
    }
}

// build funtions

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button4 = lv_button_create(ui_Screen5);
    lv_obj_set_width(ui_Button4, 40);
    lv_obj_set_height(ui_Button4, 40);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label15 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Back");

    ui_Panel4 = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_Panel4, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Panel4, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Panel4, 0);
    lv_obj_set_y(ui_Panel4, -60);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label16, "Elegir carga");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_button_create(ui_Screen5);
    lv_obj_set_width(ui_Button5, 110);
    lv_obj_set_height(ui_Button5, 50);
    lv_obj_set_x(ui_Button5, 5);
    lv_obj_set_y(ui_Button5, 150);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Resistiva");

    ui_Button6 = lv_button_create(ui_Screen5);
    lv_obj_set_width(ui_Button6, 110);
    lv_obj_set_height(ui_Button6, 50);
    lv_obj_set_x(ui_Button6, 125);
    lv_obj_set_y(ui_Button6, 150);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label18 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "Inductiva");

    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);

}

void ui_Screen5_screen_destroy(void)
{
    if(ui_Screen5) lv_obj_del(ui_Screen5);

    // NULL screen variables
    ui_Screen5 = NULL;
    ui_Button4 = NULL;
    ui_Label15 = NULL;
    ui_Panel4 = NULL;
    ui_Label16 = NULL;
    ui_Button5 = NULL;
    ui_Label17 = NULL;
    ui_Button6 = NULL;
    ui_Label18 = NULL;

}
