// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: UI_TFI

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Function1 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Function2 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Function3 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Function4 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_buckImage = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Label7 = NULL;
// event funtions
void ui_event_Function1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
        _ui_screen_delete(&ui_Screen1);
    }
}

void ui_event_Function2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
        _ui_screen_delete(&ui_Screen1);
    }
}

void ui_event_Function3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen4_screen_init);
        _ui_screen_delete(&ui_Screen1);
    }
}

void ui_event_Function4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen5_screen_init);
        _ui_screen_delete(&ui_Screen1);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Function1 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Function1, 110);
    lv_obj_set_height(ui_Function1, 60);
    lv_obj_set_x(ui_Function1, 5);
    lv_obj_set_y(ui_Function1, 20);
    lv_obj_add_flag(ui_Function1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Function1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Function1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Funcion 1");

    ui_Function2 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Function2, 110);
    lv_obj_set_height(ui_Function2, 60);
    lv_obj_set_x(ui_Function2, 125);
    lv_obj_set_y(ui_Function2, 20);
    lv_obj_add_flag(ui_Function2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Function2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Function2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Funcion 2");

    ui_Function3 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Function3, 110);
    lv_obj_set_height(ui_Function3, 60);
    lv_obj_set_x(ui_Function3, 5);
    lv_obj_set_y(ui_Function3, 90);
    lv_obj_add_flag(ui_Function3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Function3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Function3);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Funcion 3");

    ui_Function4 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Function4, 110);
    lv_obj_set_height(ui_Function4, 60);
    lv_obj_set_x(ui_Function4, 125);
    lv_obj_set_y(ui_Function4, 90);
    lv_obj_add_flag(ui_Function4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Function4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Function4);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Funcion 4");

    ui_buckImage = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_buckImage, 240);
    lv_obj_set_height(ui_buckImage, 140);
    lv_obj_set_x(ui_buckImage, 0);
    lv_obj_set_y(ui_buckImage, 78);
    lv_obj_set_align(ui_buckImage, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_buckImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_buckImage, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buckImage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_image_create(ui_buckImage);
    lv_image_set_src(ui_Image2, &ui_img_buck_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image2, 140);

    ui_Label7 = lv_label_create(ui_buckImage);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label7, "Convertidor BUCK");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Function1, ui_event_Function1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Function2, ui_event_Function2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Function3, ui_event_Function3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Function4, ui_event_Function4, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Function1 = NULL;
    ui_Label4 = NULL;
    ui_Function2 = NULL;
    ui_Label5 = NULL;
    ui_Function3 = NULL;
    ui_Label6 = NULL;
    ui_Function4 = NULL;
    ui_Label1 = NULL;
    ui_buckImage = NULL;
    ui_Image2 = NULL;
    ui_Label7 = NULL;

}
