// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: UI_TFI

#include "ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Slider3 = NULL;
lv_obj_t * ui_Label12 = NULL;
// event funtions
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
        _ui_screen_delete(&ui_Screen3);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button3 = lv_button_create(ui_Screen3);
    lv_obj_set_width(ui_Button3, 40);
    lv_obj_set_height(ui_Button3, 40);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Back");

    ui_Panel2 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Panel2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, -60);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label11, "Ajuste de Ciclo de Trabajo");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider3 = lv_slider_create(ui_Screen3);
    lv_slider_set_value(ui_Slider3, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider3) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider3, 150);
    lv_obj_set_height(ui_Slider3, 10);
    lv_obj_set_x(ui_Slider3, 0);
    lv_obj_set_y(ui_Slider3, 20);
    lv_obj_set_align(ui_Slider3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider3, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider3,
                                                                                              lv_obj_get_style_pad_right(ui_Slider3, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Label12 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "text");

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Button3 = NULL;
    ui_Label3 = NULL;
    ui_Panel2 = NULL;
    ui_Label11 = NULL;
    ui_Slider3 = NULL;
    ui_Label12 = NULL;

}
