// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: UI_TFI

#include "ui.h"

lv_obj_t * ui_Screen6 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_ButtonReturn5 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_LabelTypeLoad = NULL;
// event funtions
void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        resistive_load(e);
        _ui_label_set_property(ui_LabelTypeLoad, _UI_LABEL_PROPERTY_TEXT, "Resistiva");
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        inductive_load(e);
        _ui_label_set_property(ui_LabelTypeLoad, _UI_LABEL_PROPERTY_TEXT, "Inductiva");
    }
}

void ui_event_ButtonReturn5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
        _ui_screen_delete(&ui_Screen6);
    }
}

// build funtions

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Screen6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_Screen6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Panel4 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_Panel4, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Panel4, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Panel4, 0);
    lv_obj_set_y(ui_Panel4, -60);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0xAEC8FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label16, "Elegir carga");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_button_create(ui_Screen6);
    lv_obj_set_width(ui_Button5, 110);
    lv_obj_set_height(ui_Button5, 50);
    lv_obj_set_x(ui_Button5, 5);
    lv_obj_set_y(ui_Button5, 150);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Resistiva");

    ui_Button6 = lv_button_create(ui_Screen6);
    lv_obj_set_width(ui_Button6, 110);
    lv_obj_set_height(ui_Button6, 50);
    lv_obj_set_x(ui_Button6, 125);
    lv_obj_set_y(ui_Button6, 150);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label18 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "Inductiva");

    ui_ButtonReturn5 = lv_button_create(ui_Screen6);
    lv_obj_set_width(ui_ButtonReturn5, 45);
    lv_obj_set_height(ui_ButtonReturn5, 40);
    lv_obj_add_flag(ui_ButtonReturn5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonReturn5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_ButtonReturn5, &ui_img_arrow_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_ButtonReturn5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_ButtonReturn5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -50);
    lv_obj_set_y(ui_Label12, 94);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Carga activa:");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTypeLoad = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_LabelTypeLoad, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTypeLoad, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTypeLoad, 46);
    lv_obj_set_y(ui_LabelTypeLoad, 94);
    lv_obj_set_align(ui_LabelTypeLoad, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTypeLoad, "Resistiva");
    lv_obj_set_style_text_color(ui_LabelTypeLoad, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTypeLoad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonReturn5, ui_event_ButtonReturn5, LV_EVENT_ALL, NULL);

}

void ui_Screen6_screen_destroy(void)
{
    if(ui_Screen6) lv_obj_del(ui_Screen6);

    // NULL screen variables
    ui_Screen6 = NULL;
    ui_Panel4 = NULL;
    ui_Label16 = NULL;
    ui_Button5 = NULL;
    ui_Label17 = NULL;
    ui_Button6 = NULL;
    ui_Label18 = NULL;
    ui_ButtonReturn5 = NULL;
    ui_Label12 = NULL;
    ui_LabelTypeLoad = NULL;

}
