// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: buck_UI

#include "ui.h"

void controlFixedPWM(lv_event_t * e)
{
	// Your code here
}

void controlPID(lv_event_t * e)
{
	// Your code here
}

void resistive_load(lv_event_t * e)
{
	// Your code here
}

void inductive_load(lv_event_t * e)
{
	// Your code here
}
