// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: buck_UI

#include "ui.h"

lv_obj_t * ui_buck_Button6;
lv_obj_t * ui_buck_Button5;
lv_obj_t * ui_buck_ButtonReturn5;
lv_obj_t * ui_Screen6 = NULL;
lv_obj_t * ui_ButtonReturn5 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_LabelTypeLoad = NULL;
// event funtions
void ui_event_ButtonReturn5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
        _ui_screen_delete(&ui_Screen6);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_label_set_property(ui_LabelTypeLoad, _UI_LABEL_PROPERTY_TEXT, "Resistiva");
        resistive_load(e);
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_label_set_property(ui_LabelTypeLoad, _UI_LABEL_PROPERTY_TEXT, "Inductiva");
        inductive_load(e);
    }
}

// build funtions

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonReturn5 = lv_button_create(ui_Screen6);
    lv_obj_set_width(ui_ButtonReturn5, 45);
    lv_obj_set_height(ui_ButtonReturn5, 40);
    lv_obj_add_flag(ui_ButtonReturn5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonReturn5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_ButtonReturn5, &ui_img_images_arrow_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_Panel4, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Panel4, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Panel4, -4);
    lv_obj_set_y(ui_Panel4, -68);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Elegir carga");
    lv_obj_set_style_text_align(ui_Label16, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &ui_font_fontRobotoBold18Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_button_create(ui_Screen6);
    lv_obj_set_width(ui_Button5, 110);
    lv_obj_set_height(ui_Button5, 50);
    lv_obj_set_x(ui_Button5, 5);
    lv_obj_set_y(ui_Button5, 150);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Resistiva");
    lv_obj_set_style_text_font(ui_Label17, &ui_font_fontRobotoBold16Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6 = lv_button_create(ui_Screen6);
    lv_obj_set_width(ui_Button6, 110);
    lv_obj_set_height(ui_Button6, 50);
    lv_obj_set_x(ui_Button6, 125);
    lv_obj_set_y(ui_Button6, 150);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label18 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "Inductiva");
    lv_obj_set_style_text_align(ui_Label18, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &ui_font_fontRobotoBold16Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -50);
    lv_obj_set_y(ui_Label13, 94);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Carga Activa:");
    lv_obj_set_style_text_align(ui_Label13, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &ui_font_fontRobotoRegular14Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTypeLoad = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_LabelTypeLoad, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTypeLoad, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTypeLoad, 46);
    lv_obj_set_y(ui_LabelTypeLoad, 94);
    lv_obj_set_align(ui_LabelTypeLoad, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTypeLoad, "Resistiva");
    lv_obj_set_style_text_align(ui_LabelTypeLoad, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTypeLoad, &ui_font_fontRobotoRegular14Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonReturn5, ui_event_ButtonReturn5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    ui_buck_ButtonReturn5 = ui_ButtonReturn5;
    ui_buck_Button5 = ui_Button5;
    ui_buck_Button6 = ui_Button6;

}

void ui_Screen6_screen_destroy(void)
{
    if(ui_Screen6) lv_obj_del(ui_Screen6);

    // NULL screen variables
    ui_Screen6 = NULL;
    ui_buck_ButtonReturn5 = NULL;
    ui_ButtonReturn5 = NULL;
    ui_Panel4 = NULL;
    ui_Label16 = NULL;
    ui_buck_Button5 = NULL;
    ui_Button5 = NULL;
    ui_Label17 = NULL;
    ui_buck_Button6 = NULL;
    ui_Button6 = NULL;
    ui_Label18 = NULL;
    ui_Label13 = NULL;
    ui_LabelTypeLoad = NULL;

}
