// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: buck_UI

#include "ui.h"

lv_obj_t * ui_buck_loadScreen;
lv_obj_t * ui_buck_controlScreen;
lv_obj_t * ui_buck_freqScreen;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_freqScreen = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_controlScreen = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_loadScreen = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Label4 = NULL;
// event funtions
void ui_event_freqScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
        _ui_screen_delete(&ui_Screen1);
    }
}

void ui_event_controlScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
        _ui_screen_delete(&ui_Screen1);
    }
}

void ui_event_loadScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen6_screen_init);
        _ui_screen_delete(&ui_Screen1);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_freqScreen = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_freqScreen, 110);
    lv_obj_set_height(ui_freqScreen, 60);
    lv_obj_set_x(ui_freqScreen, 5);
    lv_obj_set_y(ui_freqScreen, 80);
    lv_obj_add_flag(ui_freqScreen, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_freqScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_freqScreen);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Frecuencia de\nconmutación");
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_fontRobotoBold16Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_controlScreen = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_controlScreen, 110);
    lv_obj_set_height(ui_controlScreen, 60);
    lv_obj_set_x(ui_controlScreen, 125);
    lv_obj_set_y(ui_controlScreen, 80);
    lv_obj_add_flag(ui_controlScreen, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_controlScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_controlScreen);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Control");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_fontRobotoBold16Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_loadScreen = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_loadScreen, 110);
    lv_obj_set_height(ui_loadScreen, 60);
    lv_obj_set_x(ui_loadScreen, 5);
    lv_obj_set_y(ui_loadScreen, 150);
    lv_obj_add_flag(ui_loadScreen, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_loadScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_loadScreen);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Carga");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_fontRobotoBold16Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image1, &ui_img_images_g91_escalado_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, 100);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image1, 250);

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, -110);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Módulo convertidor\nreductor o Buck");
    lv_obj_set_style_text_align(ui_Label4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_fontRobotoBold18Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_freqScreen, ui_event_freqScreen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_controlScreen, ui_event_controlScreen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_loadScreen, ui_event_loadScreen, LV_EVENT_ALL, NULL);
    ui_buck_freqScreen = ui_freqScreen;
    ui_buck_controlScreen = ui_controlScreen;
    ui_buck_loadScreen = ui_loadScreen;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_buck_freqScreen = NULL;
    ui_freqScreen = NULL;
    ui_Label1 = NULL;
    ui_buck_controlScreen = NULL;
    ui_controlScreen = NULL;
    ui_Label2 = NULL;
    ui_buck_loadScreen = NULL;
    ui_loadScreen = NULL;
    ui_Label3 = NULL;
    ui_Image1 = NULL;
    ui_Label4 = NULL;

}
