// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: buck_UI

#include "ui.h"

lv_obj_t * ui_buck_ButtonPID;
lv_obj_t * ui_buck_ButtonPWM;
lv_obj_t * ui_buck_ButtonReturn2;
lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_ButtonReturn2 = NULL;
lv_obj_t * ui_ButtonPWM = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_ButtonPID = NULL;
lv_obj_t * ui_Label8 = NULL;
// event funtions
void ui_event_ButtonReturn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
        _ui_screen_delete(&ui_Screen3);
    }
}

void ui_event_ButtonPWM(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen4_screen_init);
        _ui_screen_delete(&ui_Screen3);
    }
    if(event_code == LV_EVENT_PRESSED) {
        controlFixedPWM(e);
    }
}

void ui_event_ButtonPID(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen5_screen_init);
        _ui_screen_delete(&ui_Screen3);
    }
    if(event_code == LV_EVENT_PRESSED) {
        controlPID(e);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonReturn2 = lv_button_create(ui_Screen3);
    lv_obj_set_width(ui_ButtonReturn2, 45);
    lv_obj_set_height(ui_ButtonReturn2, 40);
    lv_obj_add_flag(ui_ButtonReturn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonReturn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_ButtonReturn2, &ui_img_images_arrow_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonPWM = lv_button_create(ui_Screen3);
    lv_obj_set_width(ui_ButtonPWM, 100);
    lv_obj_set_height(ui_ButtonPWM, 50);
    lv_obj_set_x(ui_ButtonPWM, 0);
    lv_obj_set_y(ui_ButtonPWM, -50);
    lv_obj_set_align(ui_ButtonPWM, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonPWM, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonPWM, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_ButtonPWM);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Control Fijo\nPWM");
    lv_obj_set_style_text_align(ui_Label7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_fontMontserratM14Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonPID = lv_button_create(ui_Screen3);
    lv_obj_set_width(ui_ButtonPID, 100);
    lv_obj_set_height(ui_ButtonPID, 50);
    lv_obj_set_x(ui_ButtonPID, 0);
    lv_obj_set_y(ui_ButtonPID, 40);
    lv_obj_set_align(ui_ButtonPID, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonPID, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonPID, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_ButtonPID);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Control PID");
    lv_obj_set_style_text_align(ui_Label8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &ui_font_fontMontserratM14Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonReturn2, ui_event_ButtonReturn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonPWM, ui_event_ButtonPWM, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonPID, ui_event_ButtonPID, LV_EVENT_ALL, NULL);
    ui_buck_ButtonReturn2 = ui_ButtonReturn2;
    ui_buck_ButtonPWM = ui_ButtonPWM;
    ui_buck_ButtonPID = ui_ButtonPID;

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_buck_ButtonReturn2 = NULL;
    ui_ButtonReturn2 = NULL;
    ui_buck_ButtonPWM = NULL;
    ui_ButtonPWM = NULL;
    ui_Label7 = NULL;
    ui_buck_ButtonPID = NULL;
    ui_ButtonPID = NULL;
    ui_Label8 = NULL;

}
