// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: buck_UI

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern lv_obj_t * ui_Screen4;
extern void ui_event_ButtonReturn3(lv_event_t * e);
extern lv_obj_t * ui_ButtonReturn3;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label9;
extern void ui_event_SliderDuty(lv_event_t * e);
extern lv_obj_t * ui_SliderDuty;
extern lv_obj_t * ui_dutyPercentage;
extern void ui_event_ButtonReturnDefault2(lv_event_t * e);
extern lv_obj_t * ui_ButtonReturnDefault2;
extern lv_obj_t * ui_Label10;
// CUSTOM VARIABLES
extern lv_obj_t * ui_buck_ButtonReturn3;
extern lv_obj_t * ui_buck_SliderDuty;
extern lv_obj_t * ui_buck_ButtonReturnDefault2;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

