#ifndef GPIO_DEFINITION_H
#define GPIO_DEFINITION_H

#include "soc/gpio_num.h"

#define PIN_HP_POWER GPIO_NUM_35
#define PIN_HP_SIGNAL GPIO_NUM_42
#define PIN_MODULE_IDENT GPIO_NUM_3

#define PIN_S1 GPIO_NUM_4
#define PIN_S2 GPIO_NUM_5
#define PIN_S3 GPIO_NUM_6
#define PIN_S4 GPIO_NUM_7
#define PIN_S5 GPIO_NUM_15
#define PIN_S6 GPIO_NUM_16
#define PIN_S7 GPIO_NUM_17
#define PIN_S8 GPIO_NUM_18
#define PIN_S9 GPIO_NUM_8
#define PIN_S10 GPIO_NUM_36
#define PIN_S11 GPIO_NUM_37
#define PIN_S12 GPIO_NUM_38
#define PIN_S13 GPIO_NUM_39
#define PIN_S14 GPIO_NUM_40
#define PIN_S15 GPIO_NUM_41
#define PIN_S16 GPIO_NUM_2

#endif