// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: UI_TFI

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void controlFixedPWM(lv_event_t * e);
void controlPID(lv_event_t * e);
void resistive_load(lv_event_t * e);
void inductive_load(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
