// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: buck_UI

#include "buck_ui.h"

lv_obj_t * ui_Screen5 = NULL;
lv_obj_t * ui_ButtonReturn4 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_SliderSP = NULL;
lv_obj_t * ui_setPointValue = NULL;
lv_obj_t * ui_ButtonReturnDefault3 = NULL;
lv_obj_t * ui_Label12 = NULL;
// event funtions
void ui_event_ButtonReturn4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
        _ui_screen_delete(&ui_Screen5);
    }
}

void ui_event_SliderSP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_setPointValue, target, "", " V");
    }
}

void ui_event_ButtonReturnDefault3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_slider_set_property(ui_SliderSP, _UI_SLIDER_PROPERTY_VALUE_WITH_ANIM, 6);
        _ui_label_set_property(ui_setPointValue, _UI_LABEL_PROPERTY_TEXT, "6 V");
    }
}

// build funtions

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonReturn4 = lv_button_create(ui_Screen5);
    lv_obj_set_width(ui_ButtonReturn4, 45);
    lv_obj_set_height(ui_ButtonReturn4, 40);
    lv_obj_add_flag(ui_ButtonReturn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonReturn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_ButtonReturn4, &ui_img_images_arrow_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_Panel3, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Panel3, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, -60);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Ajuste de Control PID");
    lv_obj_set_style_text_align(ui_Label11, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &ui_font_fontMontserratM14Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderSP = lv_slider_create(ui_Screen5);
    lv_slider_set_range(ui_SliderSP, 0, 12);
    lv_slider_set_value(ui_SliderSP, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderSP) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderSP, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSP, 150);
    lv_obj_set_height(ui_SliderSP, 10);
    lv_obj_set_x(ui_SliderSP, 0);
    lv_obj_set_y(ui_SliderSP, 20);
    lv_obj_set_align(ui_SliderSP, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_SliderSP, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_SliderSP,
                                                                                               lv_obj_get_style_pad_right(ui_SliderSP, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_setPointValue = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_setPointValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setPointValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_setPointValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_setPointValue, "0 V");
    lv_obj_set_style_text_align(ui_setPointValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_setPointValue, &ui_font_fontMontserratM14Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonReturnDefault3 = lv_button_create(ui_Screen5);
    lv_obj_set_width(ui_ButtonReturnDefault3, 100);
    lv_obj_set_height(ui_ButtonReturnDefault3, 50);
    lv_obj_set_x(ui_ButtonReturnDefault3, 0);
    lv_obj_set_y(ui_ButtonReturnDefault3, 90);
    lv_obj_set_align(ui_ButtonReturnDefault3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonReturnDefault3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonReturnDefault3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label12 = lv_label_create(ui_ButtonReturnDefault3);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Valor por\ndefecto");
    lv_obj_set_style_text_align(ui_Label12, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &ui_font_fontMontserratM14Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonReturn4, ui_event_ButtonReturn4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderSP, ui_event_SliderSP, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonReturnDefault3, ui_event_ButtonReturnDefault3, LV_EVENT_ALL, NULL);

}

void ui_Screen5_screen_destroy(void)
{
    if(ui_Screen5) lv_obj_del(ui_Screen5);

    // NULL screen variables
    ui_Screen5 = NULL;
    ui_ButtonReturn4 = NULL;
    ui_Panel3 = NULL;
    ui_Label11 = NULL;
    ui_SliderSP = NULL;
    ui_setPointValue = NULL;
    ui_ButtonReturnDefault3 = NULL;
    ui_Label12 = NULL;

}
