// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: buck_UI

#include "buck_ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_ButtonReturn1 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_SliderFreq1 = NULL;
lv_obj_t * ui_freqValue = NULL;
lv_obj_t * ui_ButtonReturnDefault1 = NULL;
lv_obj_t * ui_Label6 = NULL;
// event funtions
void ui_event_ButtonReturn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
        _ui_screen_delete(&ui_Screen2);
    }
}

void ui_event_SliderFreq1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_freqValue, target, "", " kHz");
    }
}

void ui_event_ButtonReturnDefault1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_slider_set_property(ui_SliderFreq1, _UI_SLIDER_PROPERTY_VALUE_WITH_ANIM, 19);
        _ui_label_set_property(ui_freqValue, _UI_LABEL_PROPERTY_TEXT, "19 kHz");
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonReturn1 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_ButtonReturn1, 45);
    lv_obj_set_height(ui_ButtonReturn1, 40);
    lv_obj_add_flag(ui_ButtonReturn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonReturn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_ButtonReturn1, &ui_img_images_arrow_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel1, 170);
    lv_obj_set_height(ui_Panel1, 60);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, -60);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Ajuste de frecuencia\nde conmutación");
    lv_obj_set_style_text_align(ui_Label5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_fontMontserratM14Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderFreq1 = lv_slider_create(ui_Screen2);
    lv_slider_set_range(ui_SliderFreq1, 1, 19);
    lv_slider_set_value(ui_SliderFreq1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderFreq1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderFreq1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderFreq1, 150);
    lv_obj_set_height(ui_SliderFreq1, 10);
    lv_obj_set_x(ui_SliderFreq1, 0);
    lv_obj_set_y(ui_SliderFreq1, 30);
    lv_obj_set_align(ui_SliderFreq1, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_SliderFreq1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_SliderFreq1,
                                                                                                  lv_obj_get_style_pad_right(ui_SliderFreq1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_freqValue = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_freqValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_freqValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_freqValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_freqValue, "1 kHz");
    lv_obj_set_style_text_font(ui_freqValue, &ui_font_fontMontserratM14Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonReturnDefault1 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_ButtonReturnDefault1, 100);
    lv_obj_set_height(ui_ButtonReturnDefault1, 50);
    lv_obj_set_x(ui_ButtonReturnDefault1, 0);
    lv_obj_set_y(ui_ButtonReturnDefault1, 90);
    lv_obj_set_align(ui_ButtonReturnDefault1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonReturnDefault1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonReturnDefault1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_ButtonReturnDefault1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Valor por\ndefecto");
    lv_obj_set_style_text_align(ui_Label6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_fontMontserratM14Tildes, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonReturn1, ui_event_ButtonReturn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderFreq1, ui_event_SliderFreq1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonReturnDefault1, ui_event_ButtonReturnDefault1, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_ButtonReturn1 = NULL;
    ui_Panel1 = NULL;
    ui_Label5 = NULL;
    ui_SliderFreq1 = NULL;
    ui_freqValue = NULL;
    ui_ButtonReturnDefault1 = NULL;
    ui_Label6 = NULL;

}
