idf_component_register(SRCS "buck_ui.c"
                            "buck_ui_Screen1.c" 
                            "buck_ui_Screen2.c" 
                            "buck_ui_Screen3.c" 
                            "buck_ui_Screen4.c" 
                            "buck_ui_Screen5.c" 
                            "buck_ui_Screen6.c"
                            "buck_ui_events.c"
                            "buck_ui_helpers.c"
                            "buck_ui_img_images_arrow_png.c"
                            "buck_ui_img_images_buck_png.c"
                            "buck_ui_font_fontMontserratM14Tildes.c"
                            "buck_ui_font_fontMontserratM16Tildes.c"
                            "buck_ui_font_fontMontserratM18Tildes.c"
                            "buck_buck_ui_comp_hook.c"
                            "buck_buck_ui_events.c"
                    INCLUDE_DIRS "../../modules_include/ui_buck" "../../modules_include" "../../include"
                    PRIV_REQUIRES freertos esp_driver_gpio esp_lcd esp_timer lvgl__lvgl lvgl modules_src)