// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: UI_TFI

#include "ui.h"
#include "driver/gpio.h"

#include "control_state_machine.h"


#define PIN_NUM_RELAY GPIO_NUM_18

void change_load(lv_event_t * e)
{
	// Your code here
}

void resistive_load(lv_event_t * e){
	gpio_set_level(PIN_NUM_RELAY, false);
}

void inductive_load(lv_event_t * e){
	gpio_set_level(PIN_NUM_RELAY, true);
}

void controlFixedPWM(lv_event_t * e)
{
	control_mode = CONTROL_MODE_FIXED_PWM;
	//printf("Se cambió a PWM fijo");
}

void controlPID(lv_event_t * e)
{
	control_mode = CONTROL_MODE_PID;
	//printf("Se cambió a control PID");
}
