// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: UI_TFI

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_ButtonReturn1 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_SliderFreq1 = NULL;
lv_obj_t * ui_freqValue = NULL;
lv_obj_t * ui_ButtonReturnDefault1 = NULL;
lv_obj_t * ui_Label2 = NULL;
// event funtions
void ui_event_ButtonReturn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
        _ui_screen_delete(&ui_Screen2);
    }
}

void ui_event_SliderFreq1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_freqValue, target, "", " kHz");
    }
}

void ui_event_ButtonReturnDefault1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_slider_set_property(ui_SliderFreq1, _UI_SLIDER_PROPERTY_VALUE, 19);
        _ui_label_set_property(ui_freqValue, _UI_LABEL_PROPERTY_TEXT, "19 kHz");
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Screen2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_Screen2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_ButtonReturn1 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_ButtonReturn1, 45);
    lv_obj_set_height(ui_ButtonReturn1, 40);
    lv_obj_add_flag(ui_ButtonReturn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonReturn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_ButtonReturn1, &ui_img_arrow_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_ButtonReturn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_ButtonReturn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel3, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Panel3, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, -60);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0xAEC8FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label9, "Ajuste de frecuencia\nde conmutacion");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderFreq1 = lv_slider_create(ui_Screen2);
    lv_slider_set_range(ui_SliderFreq1, 1, 19);
    lv_slider_set_value(ui_SliderFreq1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderFreq1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderFreq1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderFreq1, 150);
    lv_obj_set_height(ui_SliderFreq1, 10);
    lv_obj_set_x(ui_SliderFreq1, 0);
    lv_obj_set_y(ui_SliderFreq1, 30);
    lv_obj_set_align(ui_SliderFreq1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SliderFreq1, lv_color_hex(0xAEC8FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderFreq1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_SliderFreq1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_SliderFreq1,
                                                                                                  lv_obj_get_style_pad_right(ui_SliderFreq1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_freqValue = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_freqValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_freqValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_freqValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_freqValue, "10 kHz");
    lv_obj_set_style_text_color(ui_freqValue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_freqValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonReturnDefault1 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_ButtonReturnDefault1, 100);
    lv_obj_set_height(ui_ButtonReturnDefault1, 50);
    lv_obj_set_x(ui_ButtonReturnDefault1, 0);
    lv_obj_set_y(ui_ButtonReturnDefault1, 90);
    lv_obj_set_align(ui_ButtonReturnDefault1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonReturnDefault1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonReturnDefault1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_ButtonReturnDefault1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Valor por \ndefecto");

    lv_obj_add_event_cb(ui_ButtonReturn1, ui_event_ButtonReturn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderFreq1, ui_event_SliderFreq1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonReturnDefault1, ui_event_ButtonReturnDefault1, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_ButtonReturn1 = NULL;
    ui_Panel3 = NULL;
    ui_Label9 = NULL;
    ui_SliderFreq1 = NULL;
    ui_freqValue = NULL;
    ui_ButtonReturnDefault1 = NULL;
    ui_Label2 = NULL;

}
